// Code generated by ent, DO NOT EDIT.

package usercryptoaddress

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usercryptoaddress type in the database.
	Label = "user_crypto_address"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldNetwork holds the string denoting the network field in the database.
	FieldNetwork = "network"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldDerivationIndex holds the string denoting the derivation_index field in the database.
	FieldDerivationIndex = "derivation_index"
	// FieldLastBalance holds the string denoting the last_balance field in the database.
	FieldLastBalance = "last_balance"
	// FieldLastBalanceAt holds the string denoting the last_balance_at field in the database.
	FieldLastBalanceAt = "last_balance_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usercryptoaddress in the database.
	Table = "user_crypto_addresses"
)

// Columns holds all SQL columns for usercryptoaddress fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldNetwork,
	FieldAddress,
	FieldDerivationIndex,
	FieldLastBalance,
	FieldLastBalanceAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNetwork holds the default value on creation for the "network" field.
	DefaultNetwork string
	// NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	NetworkValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultLastBalance holds the default value on creation for the "last_balance" field.
	DefaultLastBalance float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserCryptoAddress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByNetwork orders the results by the network field.
func ByNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetwork, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByDerivationIndex orders the results by the derivation_index field.
func ByDerivationIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDerivationIndex, opts...).ToFunc()
}

// ByLastBalance orders the results by the last_balance field.
func ByLastBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBalance, opts...).ToFunc()
}

// ByLastBalanceAt orders the results by the last_balance_at field.
func ByLastBalanceAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBalanceAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
