// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/cryptowalletconfig"
)

// CryptoWalletConfig is the model entity for the CryptoWalletConfig schema.
type CryptoWalletConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EncryptedMnemonic holds the value of the "encrypted_mnemonic" field.
	EncryptedMnemonic string `json:"encrypted_mnemonic,omitempty"`
	// NextDerivationIndex holds the value of the "next_derivation_index" field.
	NextDerivationIndex int64 `json:"next_derivation_index,omitempty"`
	// CollectionAddress holds the value of the "collection_address" field.
	CollectionAddress string `json:"collection_address,omitempty"`
	// FeeAddress holds the value of the "fee_address" field.
	FeeAddress string `json:"fee_address,omitempty"`
	// Initialized holds the value of the "initialized" field.
	Initialized bool `json:"initialized,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CryptoWalletConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cryptowalletconfig.FieldInitialized:
			values[i] = new(sql.NullBool)
		case cryptowalletconfig.FieldID, cryptowalletconfig.FieldNextDerivationIndex:
			values[i] = new(sql.NullInt64)
		case cryptowalletconfig.FieldEncryptedMnemonic, cryptowalletconfig.FieldCollectionAddress, cryptowalletconfig.FieldFeeAddress:
			values[i] = new(sql.NullString)
		case cryptowalletconfig.FieldCreatedAt, cryptowalletconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CryptoWalletConfig fields.
func (_m *CryptoWalletConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cryptowalletconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cryptowalletconfig.FieldEncryptedMnemonic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_mnemonic", values[i])
			} else if value.Valid {
				_m.EncryptedMnemonic = value.String
			}
		case cryptowalletconfig.FieldNextDerivationIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_derivation_index", values[i])
			} else if value.Valid {
				_m.NextDerivationIndex = value.Int64
			}
		case cryptowalletconfig.FieldCollectionAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_address", values[i])
			} else if value.Valid {
				_m.CollectionAddress = value.String
			}
		case cryptowalletconfig.FieldFeeAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fee_address", values[i])
			} else if value.Valid {
				_m.FeeAddress = value.String
			}
		case cryptowalletconfig.FieldInitialized:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field initialized", values[i])
			} else if value.Valid {
				_m.Initialized = value.Bool
			}
		case cryptowalletconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cryptowalletconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CryptoWalletConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CryptoWalletConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CryptoWalletConfig.
// Note that you need to call CryptoWalletConfig.Unwrap() before calling this method if this CryptoWalletConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CryptoWalletConfig) Update() *CryptoWalletConfigUpdateOne {
	return NewCryptoWalletConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CryptoWalletConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CryptoWalletConfig) Unwrap() *CryptoWalletConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CryptoWalletConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CryptoWalletConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CryptoWalletConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("encrypted_mnemonic=")
	builder.WriteString(_m.EncryptedMnemonic)
	builder.WriteString(", ")
	builder.WriteString("next_derivation_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextDerivationIndex))
	builder.WriteString(", ")
	builder.WriteString("collection_address=")
	builder.WriteString(_m.CollectionAddress)
	builder.WriteString(", ")
	builder.WriteString("fee_address=")
	builder.WriteString(_m.FeeAddress)
	builder.WriteString(", ")
	builder.WriteString("initialized=")
	builder.WriteString(fmt.Sprintf("%v", _m.Initialized))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CryptoWalletConfigs is a parsable slice of CryptoWalletConfig.
type CryptoWalletConfigs []*CryptoWalletConfig
