// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweeptask"
)

// CryptoSweepTaskCreate is the builder for creating a CryptoSweepTask entity.
type CryptoSweepTaskCreate struct {
	config
	mutation *CryptoSweepTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJobID sets the "job_id" field.
func (_c *CryptoSweepTaskCreate) SetJobID(v int64) *CryptoSweepTaskCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CryptoSweepTaskCreate) SetUserID(v int64) *CryptoSweepTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableUserID(v *int64) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *CryptoSweepTaskCreate) SetAddress(v string) *CryptoSweepTaskCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetDerivationIndex sets the "derivation_index" field.
func (_c *CryptoSweepTaskCreate) SetDerivationIndex(v int64) *CryptoSweepTaskCreate {
	_c.mutation.SetDerivationIndex(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CryptoSweepTaskCreate) SetAmount(v float64) *CryptoSweepTaskCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CryptoSweepTaskCreate) SetStatus(v string) *CryptoSweepTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableStatus(v *string) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGasFundTx sets the "gas_fund_tx" field.
func (_c *CryptoSweepTaskCreate) SetGasFundTx(v string) *CryptoSweepTaskCreate {
	_c.mutation.SetGasFundTx(v)
	return _c
}

// SetNillableGasFundTx sets the "gas_fund_tx" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableGasFundTx(v *string) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetGasFundTx(*v)
	}
	return _c
}

// SetSweepTx sets the "sweep_tx" field.
func (_c *CryptoSweepTaskCreate) SetSweepTx(v string) *CryptoSweepTaskCreate {
	_c.mutation.SetSweepTx(v)
	return _c
}

// SetNillableSweepTx sets the "sweep_tx" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableSweepTx(v *string) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetSweepTx(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *CryptoSweepTaskCreate) SetError(v string) *CryptoSweepTaskCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableError(v *string) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CryptoSweepTaskCreate) SetCreatedAt(v time.Time) *CryptoSweepTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableCreatedAt(v *time.Time) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CryptoSweepTaskCreate) SetUpdatedAt(v time.Time) *CryptoSweepTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CryptoSweepTaskCreate) SetNillableUpdatedAt(v *time.Time) *CryptoSweepTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CryptoSweepTaskMutation object of the builder.
func (_c *CryptoSweepTaskCreate) Mutation() *CryptoSweepTaskMutation {
	return _c.mutation
}

// Save creates the CryptoSweepTask in the database.
func (_c *CryptoSweepTaskCreate) Save(ctx context.Context) (*CryptoSweepTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CryptoSweepTaskCreate) SaveX(ctx context.Context) *CryptoSweepTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoSweepTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoSweepTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CryptoSweepTaskCreate) defaults() {
	if _, ok := _c.mutation.UserID(); !ok {
		v := cryptosweeptask.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cryptosweeptask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.GasFundTx(); !ok {
		v := cryptosweeptask.DefaultGasFundTx
		_c.mutation.SetGasFundTx(v)
	}
	if _, ok := _c.mutation.SweepTx(); !ok {
		v := cryptosweeptask.DefaultSweepTx
		_c.mutation.SetSweepTx(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := cryptosweeptask.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cryptosweeptask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cryptosweeptask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CryptoSweepTaskCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "CryptoSweepTask.job_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CryptoSweepTask.user_id"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "CryptoSweepTask.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := cryptosweeptask.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepTask.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DerivationIndex(); !ok {
		return &ValidationError{Name: "derivation_index", err: errors.New(`ent: missing required field "CryptoSweepTask.derivation_index"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CryptoSweepTask.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CryptoSweepTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cryptosweeptask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GasFundTx(); !ok {
		return &ValidationError{Name: "gas_fund_tx", err: errors.New(`ent: missing required field "CryptoSweepTask.gas_fund_tx"`)}
	}
	if v, ok := _c.mutation.GasFundTx(); ok {
		if err := cryptosweeptask.GasFundTxValidator(v); err != nil {
			return &ValidationError{Name: "gas_fund_tx", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepTask.gas_fund_tx": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SweepTx(); !ok {
		return &ValidationError{Name: "sweep_tx", err: errors.New(`ent: missing required field "CryptoSweepTask.sweep_tx"`)}
	}
	if v, ok := _c.mutation.SweepTx(); ok {
		if err := cryptosweeptask.SweepTxValidator(v); err != nil {
			return &ValidationError{Name: "sweep_tx", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepTask.sweep_tx": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "CryptoSweepTask.error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CryptoSweepTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CryptoSweepTask.updated_at"`)}
	}
	return nil
}

func (_c *CryptoSweepTaskCreate) sqlSave(ctx context.Context) (*CryptoSweepTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CryptoSweepTaskCreate) createSpec() (*CryptoSweepTask, *sqlgraph.CreateSpec) {
	var (
		_node = &CryptoSweepTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cryptosweeptask.Table, sqlgraph.NewFieldSpec(cryptosweeptask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(cryptosweeptask.FieldJobID, field.TypeInt64, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(cryptosweeptask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(cryptosweeptask.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.DerivationIndex(); ok {
		_spec.SetField(cryptosweeptask.FieldDerivationIndex, field.TypeInt64, value)
		_node.DerivationIndex = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(cryptosweeptask.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cryptosweeptask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GasFundTx(); ok {
		_spec.SetField(cryptosweeptask.FieldGasFundTx, field.TypeString, value)
		_node.GasFundTx = value
	}
	if value, ok := _c.mutation.SweepTx(); ok {
		_spec.SetField(cryptosweeptask.FieldSweepTx, field.TypeString, value)
		_node.SweepTx = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(cryptosweeptask.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cryptosweeptask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptosweeptask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoSweepTask.Create().
//		SetJobID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoSweepTaskUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoSweepTaskCreate) OnConflict(opts ...sql.ConflictOption) *CryptoSweepTaskUpsertOne {
	_c.conflict = opts
	return &CryptoSweepTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoSweepTaskCreate) OnConflictColumns(columns ...string) *CryptoSweepTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoSweepTaskUpsertOne{
		create: _c,
	}
}

type (
	// CryptoSweepTaskUpsertOne is the builder for "upsert"-ing
	//  one CryptoSweepTask node.
	CryptoSweepTaskUpsertOne struct {
		create *CryptoSweepTaskCreate
	}

	// CryptoSweepTaskUpsert is the "OnConflict" setter.
	CryptoSweepTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetJobID sets the "job_id" field.
func (u *CryptoSweepTaskUpsert) SetJobID(v int64) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldJobID, v)
	return u
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateJobID() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldJobID)
	return u
}

// AddJobID adds v to the "job_id" field.
func (u *CryptoSweepTaskUpsert) AddJobID(v int64) *CryptoSweepTaskUpsert {
	u.Add(cryptosweeptask.FieldJobID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CryptoSweepTaskUpsert) SetUserID(v int64) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateUserID() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *CryptoSweepTaskUpsert) AddUserID(v int64) *CryptoSweepTaskUpsert {
	u.Add(cryptosweeptask.FieldUserID, v)
	return u
}

// SetAddress sets the "address" field.
func (u *CryptoSweepTaskUpsert) SetAddress(v string) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateAddress() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldAddress)
	return u
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *CryptoSweepTaskUpsert) SetDerivationIndex(v int64) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldDerivationIndex, v)
	return u
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateDerivationIndex() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldDerivationIndex)
	return u
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *CryptoSweepTaskUpsert) AddDerivationIndex(v int64) *CryptoSweepTaskUpsert {
	u.Add(cryptosweeptask.FieldDerivationIndex, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *CryptoSweepTaskUpsert) SetAmount(v float64) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateAmount() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *CryptoSweepTaskUpsert) AddAmount(v float64) *CryptoSweepTaskUpsert {
	u.Add(cryptosweeptask.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *CryptoSweepTaskUpsert) SetStatus(v string) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateStatus() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldStatus)
	return u
}

// SetGasFundTx sets the "gas_fund_tx" field.
func (u *CryptoSweepTaskUpsert) SetGasFundTx(v string) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldGasFundTx, v)
	return u
}

// UpdateGasFundTx sets the "gas_fund_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateGasFundTx() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldGasFundTx)
	return u
}

// SetSweepTx sets the "sweep_tx" field.
func (u *CryptoSweepTaskUpsert) SetSweepTx(v string) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldSweepTx, v)
	return u
}

// UpdateSweepTx sets the "sweep_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateSweepTx() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldSweepTx)
	return u
}

// SetError sets the "error" field.
func (u *CryptoSweepTaskUpsert) SetError(v string) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateError() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepTaskUpsert) SetUpdatedAt(v time.Time) *CryptoSweepTaskUpsert {
	u.Set(cryptosweeptask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsert) UpdateUpdatedAt() *CryptoSweepTaskUpsert {
	u.SetExcluded(cryptosweeptask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoSweepTaskUpsertOne) UpdateNewValues() *CryptoSweepTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cryptosweeptask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CryptoSweepTaskUpsertOne) Ignore() *CryptoSweepTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoSweepTaskUpsertOne) DoNothing() *CryptoSweepTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoSweepTaskCreate.OnConflict
// documentation for more info.
func (u *CryptoSweepTaskUpsertOne) Update(set func(*CryptoSweepTaskUpsert)) *CryptoSweepTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoSweepTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *CryptoSweepTaskUpsertOne) SetJobID(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetJobID(v)
	})
}

// AddJobID adds v to the "job_id" field.
func (u *CryptoSweepTaskUpsertOne) AddJobID(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateJobID() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateJobID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CryptoSweepTaskUpsertOne) SetUserID(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CryptoSweepTaskUpsertOne) AddUserID(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateUserID() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAddress sets the "address" field.
func (u *CryptoSweepTaskUpsertOne) SetAddress(v string) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateAddress() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateAddress()
	})
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *CryptoSweepTaskUpsertOne) SetDerivationIndex(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetDerivationIndex(v)
	})
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *CryptoSweepTaskUpsertOne) AddDerivationIndex(v int64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddDerivationIndex(v)
	})
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateDerivationIndex() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateDerivationIndex()
	})
}

// SetAmount sets the "amount" field.
func (u *CryptoSweepTaskUpsertOne) SetAmount(v float64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CryptoSweepTaskUpsertOne) AddAmount(v float64) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateAmount() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoSweepTaskUpsertOne) SetStatus(v string) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateStatus() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetGasFundTx sets the "gas_fund_tx" field.
func (u *CryptoSweepTaskUpsertOne) SetGasFundTx(v string) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetGasFundTx(v)
	})
}

// UpdateGasFundTx sets the "gas_fund_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateGasFundTx() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateGasFundTx()
	})
}

// SetSweepTx sets the "sweep_tx" field.
func (u *CryptoSweepTaskUpsertOne) SetSweepTx(v string) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetSweepTx(v)
	})
}

// UpdateSweepTx sets the "sweep_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateSweepTx() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateSweepTx()
	})
}

// SetError sets the "error" field.
func (u *CryptoSweepTaskUpsertOne) SetError(v string) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateError() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepTaskUpsertOne) SetUpdatedAt(v time.Time) *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertOne) UpdateUpdatedAt() *CryptoSweepTaskUpsertOne {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoSweepTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoSweepTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoSweepTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CryptoSweepTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CryptoSweepTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CryptoSweepTaskCreateBulk is the builder for creating many CryptoSweepTask entities in bulk.
type CryptoSweepTaskCreateBulk struct {
	config
	err      error
	builders []*CryptoSweepTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the CryptoSweepTask entities in the database.
func (_c *CryptoSweepTaskCreateBulk) Save(ctx context.Context) ([]*CryptoSweepTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CryptoSweepTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CryptoSweepTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CryptoSweepTaskCreateBulk) SaveX(ctx context.Context) []*CryptoSweepTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoSweepTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoSweepTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoSweepTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoSweepTaskUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoSweepTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *CryptoSweepTaskUpsertBulk {
	_c.conflict = opts
	return &CryptoSweepTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoSweepTaskCreateBulk) OnConflictColumns(columns ...string) *CryptoSweepTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoSweepTaskUpsertBulk{
		create: _c,
	}
}

// CryptoSweepTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of CryptoSweepTask nodes.
type CryptoSweepTaskUpsertBulk struct {
	create *CryptoSweepTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoSweepTaskUpsertBulk) UpdateNewValues() *CryptoSweepTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cryptosweeptask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoSweepTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CryptoSweepTaskUpsertBulk) Ignore() *CryptoSweepTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoSweepTaskUpsertBulk) DoNothing() *CryptoSweepTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoSweepTaskCreateBulk.OnConflict
// documentation for more info.
func (u *CryptoSweepTaskUpsertBulk) Update(set func(*CryptoSweepTaskUpsert)) *CryptoSweepTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoSweepTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetJobID sets the "job_id" field.
func (u *CryptoSweepTaskUpsertBulk) SetJobID(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetJobID(v)
	})
}

// AddJobID adds v to the "job_id" field.
func (u *CryptoSweepTaskUpsertBulk) AddJobID(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddJobID(v)
	})
}

// UpdateJobID sets the "job_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateJobID() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateJobID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CryptoSweepTaskUpsertBulk) SetUserID(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *CryptoSweepTaskUpsertBulk) AddUserID(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateUserID() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAddress sets the "address" field.
func (u *CryptoSweepTaskUpsertBulk) SetAddress(v string) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateAddress() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateAddress()
	})
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *CryptoSweepTaskUpsertBulk) SetDerivationIndex(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetDerivationIndex(v)
	})
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *CryptoSweepTaskUpsertBulk) AddDerivationIndex(v int64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddDerivationIndex(v)
	})
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateDerivationIndex() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateDerivationIndex()
	})
}

// SetAmount sets the "amount" field.
func (u *CryptoSweepTaskUpsertBulk) SetAmount(v float64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *CryptoSweepTaskUpsertBulk) AddAmount(v float64) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateAmount() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoSweepTaskUpsertBulk) SetStatus(v string) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateStatus() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetGasFundTx sets the "gas_fund_tx" field.
func (u *CryptoSweepTaskUpsertBulk) SetGasFundTx(v string) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetGasFundTx(v)
	})
}

// UpdateGasFundTx sets the "gas_fund_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateGasFundTx() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateGasFundTx()
	})
}

// SetSweepTx sets the "sweep_tx" field.
func (u *CryptoSweepTaskUpsertBulk) SetSweepTx(v string) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetSweepTx(v)
	})
}

// UpdateSweepTx sets the "sweep_tx" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateSweepTx() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateSweepTx()
	})
}

// SetError sets the "error" field.
func (u *CryptoSweepTaskUpsertBulk) SetError(v string) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateError() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepTaskUpsertBulk) SetUpdatedAt(v time.Time) *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepTaskUpsertBulk) UpdateUpdatedAt() *CryptoSweepTaskUpsertBulk {
	return u.Update(func(s *CryptoSweepTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoSweepTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CryptoSweepTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoSweepTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoSweepTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
