// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptowalletconfig"
)

// CryptoWalletConfigCreate is the builder for creating a CryptoWalletConfig entity.
type CryptoWalletConfigCreate struct {
	config
	mutation *CryptoWalletConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (_c *CryptoWalletConfigCreate) SetEncryptedMnemonic(v string) *CryptoWalletConfigCreate {
	_c.mutation.SetEncryptedMnemonic(v)
	return _c
}

// SetNillableEncryptedMnemonic sets the "encrypted_mnemonic" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableEncryptedMnemonic(v *string) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetEncryptedMnemonic(*v)
	}
	return _c
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_c *CryptoWalletConfigCreate) SetNextDerivationIndex(v int64) *CryptoWalletConfigCreate {
	_c.mutation.SetNextDerivationIndex(v)
	return _c
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableNextDerivationIndex(v *int64) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetNextDerivationIndex(*v)
	}
	return _c
}

// SetCollectionAddress sets the "collection_address" field.
func (_c *CryptoWalletConfigCreate) SetCollectionAddress(v string) *CryptoWalletConfigCreate {
	_c.mutation.SetCollectionAddress(v)
	return _c
}

// SetNillableCollectionAddress sets the "collection_address" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableCollectionAddress(v *string) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetCollectionAddress(*v)
	}
	return _c
}

// SetFeeAddress sets the "fee_address" field.
func (_c *CryptoWalletConfigCreate) SetFeeAddress(v string) *CryptoWalletConfigCreate {
	_c.mutation.SetFeeAddress(v)
	return _c
}

// SetNillableFeeAddress sets the "fee_address" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableFeeAddress(v *string) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetFeeAddress(*v)
	}
	return _c
}

// SetInitialized sets the "initialized" field.
func (_c *CryptoWalletConfigCreate) SetInitialized(v bool) *CryptoWalletConfigCreate {
	_c.mutation.SetInitialized(v)
	return _c
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableInitialized(v *bool) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetInitialized(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CryptoWalletConfigCreate) SetCreatedAt(v time.Time) *CryptoWalletConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableCreatedAt(v *time.Time) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CryptoWalletConfigCreate) SetUpdatedAt(v time.Time) *CryptoWalletConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CryptoWalletConfigCreate) SetNillableUpdatedAt(v *time.Time) *CryptoWalletConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CryptoWalletConfigMutation object of the builder.
func (_c *CryptoWalletConfigCreate) Mutation() *CryptoWalletConfigMutation {
	return _c.mutation
}

// Save creates the CryptoWalletConfig in the database.
func (_c *CryptoWalletConfigCreate) Save(ctx context.Context) (*CryptoWalletConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CryptoWalletConfigCreate) SaveX(ctx context.Context) *CryptoWalletConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoWalletConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoWalletConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CryptoWalletConfigCreate) defaults() {
	if _, ok := _c.mutation.EncryptedMnemonic(); !ok {
		v := cryptowalletconfig.DefaultEncryptedMnemonic
		_c.mutation.SetEncryptedMnemonic(v)
	}
	if _, ok := _c.mutation.NextDerivationIndex(); !ok {
		v := cryptowalletconfig.DefaultNextDerivationIndex
		_c.mutation.SetNextDerivationIndex(v)
	}
	if _, ok := _c.mutation.CollectionAddress(); !ok {
		v := cryptowalletconfig.DefaultCollectionAddress
		_c.mutation.SetCollectionAddress(v)
	}
	if _, ok := _c.mutation.FeeAddress(); !ok {
		v := cryptowalletconfig.DefaultFeeAddress
		_c.mutation.SetFeeAddress(v)
	}
	if _, ok := _c.mutation.Initialized(); !ok {
		v := cryptowalletconfig.DefaultInitialized
		_c.mutation.SetInitialized(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cryptowalletconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cryptowalletconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CryptoWalletConfigCreate) check() error {
	if _, ok := _c.mutation.EncryptedMnemonic(); !ok {
		return &ValidationError{Name: "encrypted_mnemonic", err: errors.New(`ent: missing required field "CryptoWalletConfig.encrypted_mnemonic"`)}
	}
	if _, ok := _c.mutation.NextDerivationIndex(); !ok {
		return &ValidationError{Name: "next_derivation_index", err: errors.New(`ent: missing required field "CryptoWalletConfig.next_derivation_index"`)}
	}
	if _, ok := _c.mutation.CollectionAddress(); !ok {
		return &ValidationError{Name: "collection_address", err: errors.New(`ent: missing required field "CryptoWalletConfig.collection_address"`)}
	}
	if v, ok := _c.mutation.CollectionAddress(); ok {
		if err := cryptowalletconfig.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.collection_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FeeAddress(); !ok {
		return &ValidationError{Name: "fee_address", err: errors.New(`ent: missing required field "CryptoWalletConfig.fee_address"`)}
	}
	if v, ok := _c.mutation.FeeAddress(); ok {
		if err := cryptowalletconfig.FeeAddressValidator(v); err != nil {
			return &ValidationError{Name: "fee_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.fee_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Initialized(); !ok {
		return &ValidationError{Name: "initialized", err: errors.New(`ent: missing required field "CryptoWalletConfig.initialized"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CryptoWalletConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CryptoWalletConfig.updated_at"`)}
	}
	return nil
}

func (_c *CryptoWalletConfigCreate) sqlSave(ctx context.Context) (*CryptoWalletConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CryptoWalletConfigCreate) createSpec() (*CryptoWalletConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &CryptoWalletConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cryptowalletconfig.Table, sqlgraph.NewFieldSpec(cryptowalletconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.EncryptedMnemonic(); ok {
		_spec.SetField(cryptowalletconfig.FieldEncryptedMnemonic, field.TypeString, value)
		_node.EncryptedMnemonic = value
	}
	if value, ok := _c.mutation.NextDerivationIndex(); ok {
		_spec.SetField(cryptowalletconfig.FieldNextDerivationIndex, field.TypeInt64, value)
		_node.NextDerivationIndex = value
	}
	if value, ok := _c.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldCollectionAddress, field.TypeString, value)
		_node.CollectionAddress = value
	}
	if value, ok := _c.mutation.FeeAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldFeeAddress, field.TypeString, value)
		_node.FeeAddress = value
	}
	if value, ok := _c.mutation.Initialized(); ok {
		_spec.SetField(cryptowalletconfig.FieldInitialized, field.TypeBool, value)
		_node.Initialized = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cryptowalletconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptowalletconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoWalletConfig.Create().
//		SetEncryptedMnemonic(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoWalletConfigUpsert) {
//			SetEncryptedMnemonic(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoWalletConfigCreate) OnConflict(opts ...sql.ConflictOption) *CryptoWalletConfigUpsertOne {
	_c.conflict = opts
	return &CryptoWalletConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoWalletConfigCreate) OnConflictColumns(columns ...string) *CryptoWalletConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoWalletConfigUpsertOne{
		create: _c,
	}
}

type (
	// CryptoWalletConfigUpsertOne is the builder for "upsert"-ing
	//  one CryptoWalletConfig node.
	CryptoWalletConfigUpsertOne struct {
		create *CryptoWalletConfigCreate
	}

	// CryptoWalletConfigUpsert is the "OnConflict" setter.
	CryptoWalletConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (u *CryptoWalletConfigUpsert) SetEncryptedMnemonic(v string) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldEncryptedMnemonic, v)
	return u
}

// UpdateEncryptedMnemonic sets the "encrypted_mnemonic" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateEncryptedMnemonic() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldEncryptedMnemonic)
	return u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsert) SetNextDerivationIndex(v int64) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldNextDerivationIndex, v)
	return u
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateNextDerivationIndex() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldNextDerivationIndex)
	return u
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsert) AddNextDerivationIndex(v int64) *CryptoWalletConfigUpsert {
	u.Add(cryptowalletconfig.FieldNextDerivationIndex, v)
	return u
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoWalletConfigUpsert) SetCollectionAddress(v string) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldCollectionAddress, v)
	return u
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateCollectionAddress() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldCollectionAddress)
	return u
}

// SetFeeAddress sets the "fee_address" field.
func (u *CryptoWalletConfigUpsert) SetFeeAddress(v string) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldFeeAddress, v)
	return u
}

// UpdateFeeAddress sets the "fee_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateFeeAddress() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldFeeAddress)
	return u
}

// SetInitialized sets the "initialized" field.
func (u *CryptoWalletConfigUpsert) SetInitialized(v bool) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldInitialized, v)
	return u
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateInitialized() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldInitialized)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoWalletConfigUpsert) SetUpdatedAt(v time.Time) *CryptoWalletConfigUpsert {
	u.Set(cryptowalletconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsert) UpdateUpdatedAt() *CryptoWalletConfigUpsert {
	u.SetExcluded(cryptowalletconfig.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoWalletConfigUpsertOne) UpdateNewValues() *CryptoWalletConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cryptowalletconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CryptoWalletConfigUpsertOne) Ignore() *CryptoWalletConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoWalletConfigUpsertOne) DoNothing() *CryptoWalletConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoWalletConfigCreate.OnConflict
// documentation for more info.
func (u *CryptoWalletConfigUpsertOne) Update(set func(*CryptoWalletConfigUpsert)) *CryptoWalletConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoWalletConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (u *CryptoWalletConfigUpsertOne) SetEncryptedMnemonic(v string) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetEncryptedMnemonic(v)
	})
}

// UpdateEncryptedMnemonic sets the "encrypted_mnemonic" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateEncryptedMnemonic() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateEncryptedMnemonic()
	})
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsertOne) SetNextDerivationIndex(v int64) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetNextDerivationIndex(v)
	})
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsertOne) AddNextDerivationIndex(v int64) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.AddNextDerivationIndex(v)
	})
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateNextDerivationIndex() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateNextDerivationIndex()
	})
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoWalletConfigUpsertOne) SetCollectionAddress(v string) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetCollectionAddress(v)
	})
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateCollectionAddress() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateCollectionAddress()
	})
}

// SetFeeAddress sets the "fee_address" field.
func (u *CryptoWalletConfigUpsertOne) SetFeeAddress(v string) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetFeeAddress(v)
	})
}

// UpdateFeeAddress sets the "fee_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateFeeAddress() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateFeeAddress()
	})
}

// SetInitialized sets the "initialized" field.
func (u *CryptoWalletConfigUpsertOne) SetInitialized(v bool) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetInitialized(v)
	})
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateInitialized() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateInitialized()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoWalletConfigUpsertOne) SetUpdatedAt(v time.Time) *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertOne) UpdateUpdatedAt() *CryptoWalletConfigUpsertOne {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoWalletConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoWalletConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoWalletConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CryptoWalletConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CryptoWalletConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CryptoWalletConfigCreateBulk is the builder for creating many CryptoWalletConfig entities in bulk.
type CryptoWalletConfigCreateBulk struct {
	config
	err      error
	builders []*CryptoWalletConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the CryptoWalletConfig entities in the database.
func (_c *CryptoWalletConfigCreateBulk) Save(ctx context.Context) ([]*CryptoWalletConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CryptoWalletConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CryptoWalletConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CryptoWalletConfigCreateBulk) SaveX(ctx context.Context) []*CryptoWalletConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoWalletConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoWalletConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoWalletConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoWalletConfigUpsert) {
//			SetEncryptedMnemonic(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoWalletConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *CryptoWalletConfigUpsertBulk {
	_c.conflict = opts
	return &CryptoWalletConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoWalletConfigCreateBulk) OnConflictColumns(columns ...string) *CryptoWalletConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoWalletConfigUpsertBulk{
		create: _c,
	}
}

// CryptoWalletConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of CryptoWalletConfig nodes.
type CryptoWalletConfigUpsertBulk struct {
	create *CryptoWalletConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoWalletConfigUpsertBulk) UpdateNewValues() *CryptoWalletConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cryptowalletconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoWalletConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CryptoWalletConfigUpsertBulk) Ignore() *CryptoWalletConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoWalletConfigUpsertBulk) DoNothing() *CryptoWalletConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoWalletConfigCreateBulk.OnConflict
// documentation for more info.
func (u *CryptoWalletConfigUpsertBulk) Update(set func(*CryptoWalletConfigUpsert)) *CryptoWalletConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoWalletConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (u *CryptoWalletConfigUpsertBulk) SetEncryptedMnemonic(v string) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetEncryptedMnemonic(v)
	})
}

// UpdateEncryptedMnemonic sets the "encrypted_mnemonic" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateEncryptedMnemonic() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateEncryptedMnemonic()
	})
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsertBulk) SetNextDerivationIndex(v int64) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetNextDerivationIndex(v)
	})
}

// AddNextDerivationIndex adds v to the "next_derivation_index" field.
func (u *CryptoWalletConfigUpsertBulk) AddNextDerivationIndex(v int64) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.AddNextDerivationIndex(v)
	})
}

// UpdateNextDerivationIndex sets the "next_derivation_index" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateNextDerivationIndex() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateNextDerivationIndex()
	})
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoWalletConfigUpsertBulk) SetCollectionAddress(v string) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetCollectionAddress(v)
	})
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateCollectionAddress() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateCollectionAddress()
	})
}

// SetFeeAddress sets the "fee_address" field.
func (u *CryptoWalletConfigUpsertBulk) SetFeeAddress(v string) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetFeeAddress(v)
	})
}

// UpdateFeeAddress sets the "fee_address" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateFeeAddress() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateFeeAddress()
	})
}

// SetInitialized sets the "initialized" field.
func (u *CryptoWalletConfigUpsertBulk) SetInitialized(v bool) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetInitialized(v)
	})
}

// UpdateInitialized sets the "initialized" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateInitialized() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateInitialized()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoWalletConfigUpsertBulk) SetUpdatedAt(v time.Time) *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoWalletConfigUpsertBulk) UpdateUpdatedAt() *CryptoWalletConfigUpsertBulk {
	return u.Update(func(s *CryptoWalletConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CryptoWalletConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CryptoWalletConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoWalletConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoWalletConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
