// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweeptask"
)

// CryptoSweepTask is the model entity for the CryptoSweepTask schema.
type CryptoSweepTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID int64 `json:"job_id,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// DerivationIndex holds the value of the "derivation_index" field.
	DerivationIndex int64 `json:"derivation_index,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// GasFundTx holds the value of the "gas_fund_tx" field.
	GasFundTx string `json:"gas_fund_tx,omitempty"`
	// SweepTx holds the value of the "sweep_tx" field.
	SweepTx string `json:"sweep_tx,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CryptoSweepTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cryptosweeptask.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case cryptosweeptask.FieldID, cryptosweeptask.FieldJobID, cryptosweeptask.FieldUserID, cryptosweeptask.FieldDerivationIndex:
			values[i] = new(sql.NullInt64)
		case cryptosweeptask.FieldNetwork, cryptosweeptask.FieldAddress, cryptosweeptask.FieldStatus, cryptosweeptask.FieldGasFundTx, cryptosweeptask.FieldSweepTx, cryptosweeptask.FieldError:
			values[i] = new(sql.NullString)
		case cryptosweeptask.FieldCreatedAt, cryptosweeptask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CryptoSweepTask fields.
func (_m *CryptoSweepTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cryptosweeptask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cryptosweeptask.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.Int64
			}
		case cryptosweeptask.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case cryptosweeptask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case cryptosweeptask.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case cryptosweeptask.FieldDerivationIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field derivation_index", values[i])
			} else if value.Valid {
				_m.DerivationIndex = value.Int64
			}
		case cryptosweeptask.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case cryptosweeptask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case cryptosweeptask.FieldGasFundTx:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field gas_fund_tx", values[i])
			} else if value.Valid {
				_m.GasFundTx = value.String
			}
		case cryptosweeptask.FieldSweepTx:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sweep_tx", values[i])
			} else if value.Valid {
				_m.SweepTx = value.String
			}
		case cryptosweeptask.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case cryptosweeptask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cryptosweeptask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CryptoSweepTask.
// This includes values selected through modifiers, order, etc.
func (_m *CryptoSweepTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CryptoSweepTask.
// Note that you need to call CryptoSweepTask.Unwrap() before calling this method if this CryptoSweepTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CryptoSweepTask) Update() *CryptoSweepTaskUpdateOne {
	return NewCryptoSweepTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CryptoSweepTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CryptoSweepTask) Unwrap() *CryptoSweepTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CryptoSweepTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CryptoSweepTask) String() string {
	var builder strings.Builder
	builder.WriteString("CryptoSweepTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("derivation_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.DerivationIndex))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("gas_fund_tx=")
	builder.WriteString(_m.GasFundTx)
	builder.WriteString(", ")
	builder.WriteString("sweep_tx=")
	builder.WriteString(_m.SweepTx)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CryptoSweepTasks is a parsable slice of CryptoSweepTask.
type CryptoSweepTasks []*CryptoSweepTask
