// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweepjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CryptoSweepJobDelete is the builder for deleting a CryptoSweepJob entity.
type CryptoSweepJobDelete struct {
	config
	hooks    []Hook
	mutation *CryptoSweepJobMutation
}

// Where appends a list predicates to the CryptoSweepJobDelete builder.
func (_d *CryptoSweepJobDelete) Where(ps ...predicate.CryptoSweepJob) *CryptoSweepJobDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CryptoSweepJobDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CryptoSweepJobDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CryptoSweepJobDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cryptosweepjob.Table, sqlgraph.NewFieldSpec(cryptosweepjob.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CryptoSweepJobDeleteOne is the builder for deleting a single CryptoSweepJob entity.
type CryptoSweepJobDeleteOne struct {
	_d *CryptoSweepJobDelete
}

// Where appends a list predicates to the CryptoSweepJobDelete builder.
func (_d *CryptoSweepJobDeleteOne) Where(ps ...predicate.CryptoSweepJob) *CryptoSweepJobDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CryptoSweepJobDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cryptosweepjob.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CryptoSweepJobDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
