// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptowalletconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CryptoWalletConfigUpdate is the builder for updating CryptoWalletConfig entities.
type CryptoWalletConfigUpdate struct {
	config
	hooks    []Hook
	mutation *CryptoWalletConfigMutation
}

// Where appends a list predicates to the CryptoWalletConfigUpdate builder.
func (_u *CryptoWalletConfigUpdate) Where(ps ...predicate.CryptoWalletConfig) *CryptoWalletConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (_u *CryptoWalletConfigUpdate) SetEncryptedMnemonic(v string) *CryptoWalletConfigUpdate {
	_u.mutation.SetEncryptedMnemonic(v)
	return _u
}

// SetNillableEncryptedMnemonic sets the "encrypted_mnemonic" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdate) SetNillableEncryptedMnemonic(v *string) *CryptoWalletConfigUpdate {
	if v != nil {
		_u.SetEncryptedMnemonic(*v)
	}
	return _u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_u *CryptoWalletConfigUpdate) SetNextDerivationIndex(v int64) *CryptoWalletConfigUpdate {
	_u.mutation.ResetNextDerivationIndex()
	_u.mutation.SetNextDerivationIndex(v)
	return _u
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdate) SetNillableNextDerivationIndex(v *int64) *CryptoWalletConfigUpdate {
	if v != nil {
		_u.SetNextDerivationIndex(*v)
	}
	return _u
}

// AddNextDerivationIndex adds value to the "next_derivation_index" field.
func (_u *CryptoWalletConfigUpdate) AddNextDerivationIndex(v int64) *CryptoWalletConfigUpdate {
	_u.mutation.AddNextDerivationIndex(v)
	return _u
}

// SetCollectionAddress sets the "collection_address" field.
func (_u *CryptoWalletConfigUpdate) SetCollectionAddress(v string) *CryptoWalletConfigUpdate {
	_u.mutation.SetCollectionAddress(v)
	return _u
}

// SetNillableCollectionAddress sets the "collection_address" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdate) SetNillableCollectionAddress(v *string) *CryptoWalletConfigUpdate {
	if v != nil {
		_u.SetCollectionAddress(*v)
	}
	return _u
}

// SetFeeAddress sets the "fee_address" field.
func (_u *CryptoWalletConfigUpdate) SetFeeAddress(v string) *CryptoWalletConfigUpdate {
	_u.mutation.SetFeeAddress(v)
	return _u
}

// SetNillableFeeAddress sets the "fee_address" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdate) SetNillableFeeAddress(v *string) *CryptoWalletConfigUpdate {
	if v != nil {
		_u.SetFeeAddress(*v)
	}
	return _u
}

// SetInitialized sets the "initialized" field.
func (_u *CryptoWalletConfigUpdate) SetInitialized(v bool) *CryptoWalletConfigUpdate {
	_u.mutation.SetInitialized(v)
	return _u
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdate) SetNillableInitialized(v *bool) *CryptoWalletConfigUpdate {
	if v != nil {
		_u.SetInitialized(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoWalletConfigUpdate) SetUpdatedAt(v time.Time) *CryptoWalletConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CryptoWalletConfigMutation object of the builder.
func (_u *CryptoWalletConfigUpdate) Mutation() *CryptoWalletConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CryptoWalletConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoWalletConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CryptoWalletConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoWalletConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoWalletConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptowalletconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoWalletConfigUpdate) check() error {
	if v, ok := _u.mutation.CollectionAddress(); ok {
		if err := cryptowalletconfig.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.collection_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeeAddress(); ok {
		if err := cryptowalletconfig.FeeAddressValidator(v); err != nil {
			return &ValidationError{Name: "fee_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.fee_address": %w`, err)}
		}
	}
	return nil
}

func (_u *CryptoWalletConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptowalletconfig.Table, cryptowalletconfig.Columns, sqlgraph.NewFieldSpec(cryptowalletconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EncryptedMnemonic(); ok {
		_spec.SetField(cryptowalletconfig.FieldEncryptedMnemonic, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextDerivationIndex(); ok {
		_spec.SetField(cryptowalletconfig.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextDerivationIndex(); ok {
		_spec.AddField(cryptowalletconfig.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldCollectionAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeeAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldFeeAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initialized(); ok {
		_spec.SetField(cryptowalletconfig.FieldInitialized, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptowalletconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptowalletconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CryptoWalletConfigUpdateOne is the builder for updating a single CryptoWalletConfig entity.
type CryptoWalletConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CryptoWalletConfigMutation
}

// SetEncryptedMnemonic sets the "encrypted_mnemonic" field.
func (_u *CryptoWalletConfigUpdateOne) SetEncryptedMnemonic(v string) *CryptoWalletConfigUpdateOne {
	_u.mutation.SetEncryptedMnemonic(v)
	return _u
}

// SetNillableEncryptedMnemonic sets the "encrypted_mnemonic" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdateOne) SetNillableEncryptedMnemonic(v *string) *CryptoWalletConfigUpdateOne {
	if v != nil {
		_u.SetEncryptedMnemonic(*v)
	}
	return _u
}

// SetNextDerivationIndex sets the "next_derivation_index" field.
func (_u *CryptoWalletConfigUpdateOne) SetNextDerivationIndex(v int64) *CryptoWalletConfigUpdateOne {
	_u.mutation.ResetNextDerivationIndex()
	_u.mutation.SetNextDerivationIndex(v)
	return _u
}

// SetNillableNextDerivationIndex sets the "next_derivation_index" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdateOne) SetNillableNextDerivationIndex(v *int64) *CryptoWalletConfigUpdateOne {
	if v != nil {
		_u.SetNextDerivationIndex(*v)
	}
	return _u
}

// AddNextDerivationIndex adds value to the "next_derivation_index" field.
func (_u *CryptoWalletConfigUpdateOne) AddNextDerivationIndex(v int64) *CryptoWalletConfigUpdateOne {
	_u.mutation.AddNextDerivationIndex(v)
	return _u
}

// SetCollectionAddress sets the "collection_address" field.
func (_u *CryptoWalletConfigUpdateOne) SetCollectionAddress(v string) *CryptoWalletConfigUpdateOne {
	_u.mutation.SetCollectionAddress(v)
	return _u
}

// SetNillableCollectionAddress sets the "collection_address" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdateOne) SetNillableCollectionAddress(v *string) *CryptoWalletConfigUpdateOne {
	if v != nil {
		_u.SetCollectionAddress(*v)
	}
	return _u
}

// SetFeeAddress sets the "fee_address" field.
func (_u *CryptoWalletConfigUpdateOne) SetFeeAddress(v string) *CryptoWalletConfigUpdateOne {
	_u.mutation.SetFeeAddress(v)
	return _u
}

// SetNillableFeeAddress sets the "fee_address" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdateOne) SetNillableFeeAddress(v *string) *CryptoWalletConfigUpdateOne {
	if v != nil {
		_u.SetFeeAddress(*v)
	}
	return _u
}

// SetInitialized sets the "initialized" field.
func (_u *CryptoWalletConfigUpdateOne) SetInitialized(v bool) *CryptoWalletConfigUpdateOne {
	_u.mutation.SetInitialized(v)
	return _u
}

// SetNillableInitialized sets the "initialized" field if the given value is not nil.
func (_u *CryptoWalletConfigUpdateOne) SetNillableInitialized(v *bool) *CryptoWalletConfigUpdateOne {
	if v != nil {
		_u.SetInitialized(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoWalletConfigUpdateOne) SetUpdatedAt(v time.Time) *CryptoWalletConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CryptoWalletConfigMutation object of the builder.
func (_u *CryptoWalletConfigUpdateOne) Mutation() *CryptoWalletConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the CryptoWalletConfigUpdate builder.
func (_u *CryptoWalletConfigUpdateOne) Where(ps ...predicate.CryptoWalletConfig) *CryptoWalletConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CryptoWalletConfigUpdateOne) Select(field string, fields ...string) *CryptoWalletConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CryptoWalletConfig entity.
func (_u *CryptoWalletConfigUpdateOne) Save(ctx context.Context) (*CryptoWalletConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoWalletConfigUpdateOne) SaveX(ctx context.Context) *CryptoWalletConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CryptoWalletConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoWalletConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoWalletConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptowalletconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoWalletConfigUpdateOne) check() error {
	if v, ok := _u.mutation.CollectionAddress(); ok {
		if err := cryptowalletconfig.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.collection_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FeeAddress(); ok {
		if err := cryptowalletconfig.FeeAddressValidator(v); err != nil {
			return &ValidationError{Name: "fee_address", err: fmt.Errorf(`ent: validator failed for field "CryptoWalletConfig.fee_address": %w`, err)}
		}
	}
	return nil
}

func (_u *CryptoWalletConfigUpdateOne) sqlSave(ctx context.Context) (_node *CryptoWalletConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptowalletconfig.Table, cryptowalletconfig.Columns, sqlgraph.NewFieldSpec(cryptowalletconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CryptoWalletConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cryptowalletconfig.FieldID)
		for _, f := range fields {
			if !cryptowalletconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cryptowalletconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EncryptedMnemonic(); ok {
		_spec.SetField(cryptowalletconfig.FieldEncryptedMnemonic, field.TypeString, value)
	}
	if value, ok := _u.mutation.NextDerivationIndex(); ok {
		_spec.SetField(cryptowalletconfig.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedNextDerivationIndex(); ok {
		_spec.AddField(cryptowalletconfig.FieldNextDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldCollectionAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FeeAddress(); ok {
		_spec.SetField(cryptowalletconfig.FieldFeeAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initialized(); ok {
		_spec.SetField(cryptowalletconfig.FieldInitialized, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptowalletconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CryptoWalletConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptowalletconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
