// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweepjob"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CryptoSweepJobUpdate is the builder for updating CryptoSweepJob entities.
type CryptoSweepJobUpdate struct {
	config
	hooks    []Hook
	mutation *CryptoSweepJobMutation
}

// Where appends a list predicates to the CryptoSweepJobUpdate builder.
func (_u *CryptoSweepJobUpdate) Where(ps ...predicate.CryptoSweepJob) *CryptoSweepJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *CryptoSweepJobUpdate) SetStatus(v string) *CryptoSweepJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableStatus(v *string) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CryptoSweepJobUpdate) SetCreatedBy(v string) *CryptoSweepJobUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableCreatedBy(v *string) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetTotalTasks sets the "total_tasks" field.
func (_u *CryptoSweepJobUpdate) SetTotalTasks(v int) *CryptoSweepJobUpdate {
	_u.mutation.ResetTotalTasks()
	_u.mutation.SetTotalTasks(v)
	return _u
}

// SetNillableTotalTasks sets the "total_tasks" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableTotalTasks(v *int) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetTotalTasks(*v)
	}
	return _u
}

// AddTotalTasks adds value to the "total_tasks" field.
func (_u *CryptoSweepJobUpdate) AddTotalTasks(v int) *CryptoSweepJobUpdate {
	_u.mutation.AddTotalTasks(v)
	return _u
}

// SetCompletedTasks sets the "completed_tasks" field.
func (_u *CryptoSweepJobUpdate) SetCompletedTasks(v int) *CryptoSweepJobUpdate {
	_u.mutation.ResetCompletedTasks()
	_u.mutation.SetCompletedTasks(v)
	return _u
}

// SetNillableCompletedTasks sets the "completed_tasks" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableCompletedTasks(v *int) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetCompletedTasks(*v)
	}
	return _u
}

// AddCompletedTasks adds value to the "completed_tasks" field.
func (_u *CryptoSweepJobUpdate) AddCompletedTasks(v int) *CryptoSweepJobUpdate {
	_u.mutation.AddCompletedTasks(v)
	return _u
}

// SetTotalSwept sets the "total_swept" field.
func (_u *CryptoSweepJobUpdate) SetTotalSwept(v float64) *CryptoSweepJobUpdate {
	_u.mutation.ResetTotalSwept()
	_u.mutation.SetTotalSwept(v)
	return _u
}

// SetNillableTotalSwept sets the "total_swept" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableTotalSwept(v *float64) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetTotalSwept(*v)
	}
	return _u
}

// AddTotalSwept adds value to the "total_swept" field.
func (_u *CryptoSweepJobUpdate) AddTotalSwept(v float64) *CryptoSweepJobUpdate {
	_u.mutation.AddTotalSwept(v)
	return _u
}

// SetCollectionAddress sets the "collection_address" field.
func (_u *CryptoSweepJobUpdate) SetCollectionAddress(v string) *CryptoSweepJobUpdate {
	_u.mutation.SetCollectionAddress(v)
	return _u
}

// SetNillableCollectionAddress sets the "collection_address" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableCollectionAddress(v *string) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetCollectionAddress(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *CryptoSweepJobUpdate) SetError(v string) *CryptoSweepJobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableError(v *string) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoSweepJobUpdate) SetUpdatedAt(v time.Time) *CryptoSweepJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CryptoSweepJobUpdate) SetFinishedAt(v time.Time) *CryptoSweepJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CryptoSweepJobUpdate) SetNillableFinishedAt(v *time.Time) *CryptoSweepJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CryptoSweepJobUpdate) ClearFinishedAt() *CryptoSweepJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the CryptoSweepJobMutation object of the builder.
func (_u *CryptoSweepJobUpdate) Mutation() *CryptoSweepJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CryptoSweepJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoSweepJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CryptoSweepJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoSweepJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoSweepJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptosweepjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoSweepJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := cryptosweepjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := cryptosweepjob.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectionAddress(); ok {
		if err := cryptosweepjob.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.collection_address": %w`, err)}
		}
	}
	return nil
}

func (_u *CryptoSweepJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptosweepjob.Table, cryptosweepjob.Columns, sqlgraph.NewFieldSpec(cryptosweepjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cryptosweepjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(cryptosweepjob.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTasks(); ok {
		_spec.AddField(cryptosweepjob.FieldTotalTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldCompletedTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedTasks(); ok {
		_spec.AddField(cryptosweepjob.FieldCompletedTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSwept(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalSwept, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSwept(); ok {
		_spec.AddField(cryptosweepjob.FieldTotalSwept, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptosweepjob.FieldCollectionAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(cryptosweepjob.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(cryptosweepjob.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptosweepjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CryptoSweepJobUpdateOne is the builder for updating a single CryptoSweepJob entity.
type CryptoSweepJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CryptoSweepJobMutation
}

// SetStatus sets the "status" field.
func (_u *CryptoSweepJobUpdateOne) SetStatus(v string) *CryptoSweepJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableStatus(v *string) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *CryptoSweepJobUpdateOne) SetCreatedBy(v string) *CryptoSweepJobUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableCreatedBy(v *string) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetTotalTasks sets the "total_tasks" field.
func (_u *CryptoSweepJobUpdateOne) SetTotalTasks(v int) *CryptoSweepJobUpdateOne {
	_u.mutation.ResetTotalTasks()
	_u.mutation.SetTotalTasks(v)
	return _u
}

// SetNillableTotalTasks sets the "total_tasks" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableTotalTasks(v *int) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetTotalTasks(*v)
	}
	return _u
}

// AddTotalTasks adds value to the "total_tasks" field.
func (_u *CryptoSweepJobUpdateOne) AddTotalTasks(v int) *CryptoSweepJobUpdateOne {
	_u.mutation.AddTotalTasks(v)
	return _u
}

// SetCompletedTasks sets the "completed_tasks" field.
func (_u *CryptoSweepJobUpdateOne) SetCompletedTasks(v int) *CryptoSweepJobUpdateOne {
	_u.mutation.ResetCompletedTasks()
	_u.mutation.SetCompletedTasks(v)
	return _u
}

// SetNillableCompletedTasks sets the "completed_tasks" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableCompletedTasks(v *int) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetCompletedTasks(*v)
	}
	return _u
}

// AddCompletedTasks adds value to the "completed_tasks" field.
func (_u *CryptoSweepJobUpdateOne) AddCompletedTasks(v int) *CryptoSweepJobUpdateOne {
	_u.mutation.AddCompletedTasks(v)
	return _u
}

// SetTotalSwept sets the "total_swept" field.
func (_u *CryptoSweepJobUpdateOne) SetTotalSwept(v float64) *CryptoSweepJobUpdateOne {
	_u.mutation.ResetTotalSwept()
	_u.mutation.SetTotalSwept(v)
	return _u
}

// SetNillableTotalSwept sets the "total_swept" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableTotalSwept(v *float64) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetTotalSwept(*v)
	}
	return _u
}

// AddTotalSwept adds value to the "total_swept" field.
func (_u *CryptoSweepJobUpdateOne) AddTotalSwept(v float64) *CryptoSweepJobUpdateOne {
	_u.mutation.AddTotalSwept(v)
	return _u
}

// SetCollectionAddress sets the "collection_address" field.
func (_u *CryptoSweepJobUpdateOne) SetCollectionAddress(v string) *CryptoSweepJobUpdateOne {
	_u.mutation.SetCollectionAddress(v)
	return _u
}

// SetNillableCollectionAddress sets the "collection_address" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableCollectionAddress(v *string) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetCollectionAddress(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *CryptoSweepJobUpdateOne) SetError(v string) *CryptoSweepJobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableError(v *string) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CryptoSweepJobUpdateOne) SetUpdatedAt(v time.Time) *CryptoSweepJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *CryptoSweepJobUpdateOne) SetFinishedAt(v time.Time) *CryptoSweepJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *CryptoSweepJobUpdateOne) SetNillableFinishedAt(v *time.Time) *CryptoSweepJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *CryptoSweepJobUpdateOne) ClearFinishedAt() *CryptoSweepJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the CryptoSweepJobMutation object of the builder.
func (_u *CryptoSweepJobUpdateOne) Mutation() *CryptoSweepJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the CryptoSweepJobUpdate builder.
func (_u *CryptoSweepJobUpdateOne) Where(ps ...predicate.CryptoSweepJob) *CryptoSweepJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CryptoSweepJobUpdateOne) Select(field string, fields ...string) *CryptoSweepJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CryptoSweepJob entity.
func (_u *CryptoSweepJobUpdateOne) Save(ctx context.Context) (*CryptoSweepJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CryptoSweepJobUpdateOne) SaveX(ctx context.Context) *CryptoSweepJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CryptoSweepJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CryptoSweepJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CryptoSweepJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cryptosweepjob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CryptoSweepJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := cryptosweepjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CreatedBy(); ok {
		if err := cryptosweepjob.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.created_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectionAddress(); ok {
		if err := cryptosweepjob.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.collection_address": %w`, err)}
		}
	}
	return nil
}

func (_u *CryptoSweepJobUpdateOne) sqlSave(ctx context.Context) (_node *CryptoSweepJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cryptosweepjob.Table, cryptosweepjob.Columns, sqlgraph.NewFieldSpec(cryptosweepjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CryptoSweepJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cryptosweepjob.FieldID)
		for _, f := range fields {
			if !cryptosweepjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cryptosweepjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cryptosweepjob.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(cryptosweepjob.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalTasks(); ok {
		_spec.AddField(cryptosweepjob.FieldTotalTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CompletedTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldCompletedTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCompletedTasks(); ok {
		_spec.AddField(cryptosweepjob.FieldCompletedTasks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalSwept(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalSwept, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSwept(); ok {
		_spec.AddField(cryptosweepjob.FieldTotalSwept, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptosweepjob.FieldCollectionAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(cryptosweepjob.FieldError, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(cryptosweepjob.FieldFinishedAt, field.TypeTime)
	}
	_node = &CryptoSweepJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cryptosweepjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
