// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweepjob"
)

// CryptoSweepJob is the model entity for the CryptoSweepJob schema.
type CryptoSweepJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// TotalTasks holds the value of the "total_tasks" field.
	TotalTasks int `json:"total_tasks,omitempty"`
	// CompletedTasks holds the value of the "completed_tasks" field.
	CompletedTasks int `json:"completed_tasks,omitempty"`
	// TotalSwept holds the value of the "total_swept" field.
	TotalSwept float64 `json:"total_swept,omitempty"`
	// CollectionAddress holds the value of the "collection_address" field.
	CollectionAddress string `json:"collection_address,omitempty"`
	// Error holds the value of the "error" field.
	Error string `json:"error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CryptoSweepJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cryptosweepjob.FieldTotalSwept:
			values[i] = new(sql.NullFloat64)
		case cryptosweepjob.FieldID, cryptosweepjob.FieldTotalTasks, cryptosweepjob.FieldCompletedTasks:
			values[i] = new(sql.NullInt64)
		case cryptosweepjob.FieldNetwork, cryptosweepjob.FieldStatus, cryptosweepjob.FieldCreatedBy, cryptosweepjob.FieldCollectionAddress, cryptosweepjob.FieldError:
			values[i] = new(sql.NullString)
		case cryptosweepjob.FieldCreatedAt, cryptosweepjob.FieldUpdatedAt, cryptosweepjob.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CryptoSweepJob fields.
func (_m *CryptoSweepJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cryptosweepjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cryptosweepjob.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case cryptosweepjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case cryptosweepjob.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case cryptosweepjob.FieldTotalTasks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tasks", values[i])
			} else if value.Valid {
				_m.TotalTasks = int(value.Int64)
			}
		case cryptosweepjob.FieldCompletedTasks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_tasks", values[i])
			} else if value.Valid {
				_m.CompletedTasks = int(value.Int64)
			}
		case cryptosweepjob.FieldTotalSwept:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_swept", values[i])
			} else if value.Valid {
				_m.TotalSwept = value.Float64
			}
		case cryptosweepjob.FieldCollectionAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collection_address", values[i])
			} else if value.Valid {
				_m.CollectionAddress = value.String
			}
		case cryptosweepjob.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		case cryptosweepjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cryptosweepjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cryptosweepjob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CryptoSweepJob.
// This includes values selected through modifiers, order, etc.
func (_m *CryptoSweepJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CryptoSweepJob.
// Note that you need to call CryptoSweepJob.Unwrap() before calling this method if this CryptoSweepJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CryptoSweepJob) Update() *CryptoSweepJobUpdateOne {
	return NewCryptoSweepJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CryptoSweepJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CryptoSweepJob) Unwrap() *CryptoSweepJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CryptoSweepJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CryptoSweepJob) String() string {
	var builder strings.Builder
	builder.WriteString("CryptoSweepJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("total_tasks=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTasks))
	builder.WriteString(", ")
	builder.WriteString("completed_tasks=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedTasks))
	builder.WriteString(", ")
	builder.WriteString("total_swept=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSwept))
	builder.WriteString(", ")
	builder.WriteString("collection_address=")
	builder.WriteString(_m.CollectionAddress)
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CryptoSweepJobs is a parsable slice of CryptoSweepJob.
type CryptoSweepJobs []*CryptoSweepJob
