// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cryptosweepjob"
)

// CryptoSweepJobCreate is the builder for creating a CryptoSweepJob entity.
type CryptoSweepJobCreate struct {
	config
	mutation *CryptoSweepJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNetwork sets the "network" field.
func (_c *CryptoSweepJobCreate) SetNetwork(v string) *CryptoSweepJobCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableNetwork(v *string) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetNetwork(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CryptoSweepJobCreate) SetStatus(v string) *CryptoSweepJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableStatus(v *string) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *CryptoSweepJobCreate) SetCreatedBy(v string) *CryptoSweepJobCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableCreatedBy(v *string) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetTotalTasks sets the "total_tasks" field.
func (_c *CryptoSweepJobCreate) SetTotalTasks(v int) *CryptoSweepJobCreate {
	_c.mutation.SetTotalTasks(v)
	return _c
}

// SetNillableTotalTasks sets the "total_tasks" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableTotalTasks(v *int) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetTotalTasks(*v)
	}
	return _c
}

// SetCompletedTasks sets the "completed_tasks" field.
func (_c *CryptoSweepJobCreate) SetCompletedTasks(v int) *CryptoSweepJobCreate {
	_c.mutation.SetCompletedTasks(v)
	return _c
}

// SetNillableCompletedTasks sets the "completed_tasks" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableCompletedTasks(v *int) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetCompletedTasks(*v)
	}
	return _c
}

// SetTotalSwept sets the "total_swept" field.
func (_c *CryptoSweepJobCreate) SetTotalSwept(v float64) *CryptoSweepJobCreate {
	_c.mutation.SetTotalSwept(v)
	return _c
}

// SetNillableTotalSwept sets the "total_swept" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableTotalSwept(v *float64) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetTotalSwept(*v)
	}
	return _c
}

// SetCollectionAddress sets the "collection_address" field.
func (_c *CryptoSweepJobCreate) SetCollectionAddress(v string) *CryptoSweepJobCreate {
	_c.mutation.SetCollectionAddress(v)
	return _c
}

// SetError sets the "error" field.
func (_c *CryptoSweepJobCreate) SetError(v string) *CryptoSweepJobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableError(v *string) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CryptoSweepJobCreate) SetCreatedAt(v time.Time) *CryptoSweepJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableCreatedAt(v *time.Time) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CryptoSweepJobCreate) SetUpdatedAt(v time.Time) *CryptoSweepJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableUpdatedAt(v *time.Time) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *CryptoSweepJobCreate) SetFinishedAt(v time.Time) *CryptoSweepJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *CryptoSweepJobCreate) SetNillableFinishedAt(v *time.Time) *CryptoSweepJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the CryptoSweepJobMutation object of the builder.
func (_c *CryptoSweepJobCreate) Mutation() *CryptoSweepJobMutation {
	return _c.mutation
}

// Save creates the CryptoSweepJob in the database.
func (_c *CryptoSweepJobCreate) Save(ctx context.Context) (*CryptoSweepJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CryptoSweepJobCreate) SaveX(ctx context.Context) *CryptoSweepJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoSweepJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoSweepJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CryptoSweepJobCreate) defaults() {
	if _, ok := _c.mutation.Network(); !ok {
		v := cryptosweepjob.DefaultNetwork
		_c.mutation.SetNetwork(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cryptosweepjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		v := cryptosweepjob.DefaultCreatedBy
		_c.mutation.SetCreatedBy(v)
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		v := cryptosweepjob.DefaultTotalTasks
		_c.mutation.SetTotalTasks(v)
	}
	if _, ok := _c.mutation.CompletedTasks(); !ok {
		v := cryptosweepjob.DefaultCompletedTasks
		_c.mutation.SetCompletedTasks(v)
	}
	if _, ok := _c.mutation.TotalSwept(); !ok {
		v := cryptosweepjob.DefaultTotalSwept
		_c.mutation.SetTotalSwept(v)
	}
	if _, ok := _c.mutation.Error(); !ok {
		v := cryptosweepjob.DefaultError
		_c.mutation.SetError(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cryptosweepjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cryptosweepjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CryptoSweepJobCreate) check() error {
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "CryptoSweepJob.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := cryptosweepjob.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CryptoSweepJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := cryptosweepjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "CryptoSweepJob.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := cryptosweepjob.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalTasks(); !ok {
		return &ValidationError{Name: "total_tasks", err: errors.New(`ent: missing required field "CryptoSweepJob.total_tasks"`)}
	}
	if _, ok := _c.mutation.CompletedTasks(); !ok {
		return &ValidationError{Name: "completed_tasks", err: errors.New(`ent: missing required field "CryptoSweepJob.completed_tasks"`)}
	}
	if _, ok := _c.mutation.TotalSwept(); !ok {
		return &ValidationError{Name: "total_swept", err: errors.New(`ent: missing required field "CryptoSweepJob.total_swept"`)}
	}
	if _, ok := _c.mutation.CollectionAddress(); !ok {
		return &ValidationError{Name: "collection_address", err: errors.New(`ent: missing required field "CryptoSweepJob.collection_address"`)}
	}
	if v, ok := _c.mutation.CollectionAddress(); ok {
		if err := cryptosweepjob.CollectionAddressValidator(v); err != nil {
			return &ValidationError{Name: "collection_address", err: fmt.Errorf(`ent: validator failed for field "CryptoSweepJob.collection_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Error(); !ok {
		return &ValidationError{Name: "error", err: errors.New(`ent: missing required field "CryptoSweepJob.error"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CryptoSweepJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CryptoSweepJob.updated_at"`)}
	}
	return nil
}

func (_c *CryptoSweepJobCreate) sqlSave(ctx context.Context) (*CryptoSweepJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CryptoSweepJobCreate) createSpec() (*CryptoSweepJob, *sqlgraph.CreateSpec) {
	var (
		_node = &CryptoSweepJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cryptosweepjob.Table, sqlgraph.NewFieldSpec(cryptosweepjob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(cryptosweepjob.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cryptosweepjob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(cryptosweepjob.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.TotalTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalTasks, field.TypeInt, value)
		_node.TotalTasks = value
	}
	if value, ok := _c.mutation.CompletedTasks(); ok {
		_spec.SetField(cryptosweepjob.FieldCompletedTasks, field.TypeInt, value)
		_node.CompletedTasks = value
	}
	if value, ok := _c.mutation.TotalSwept(); ok {
		_spec.SetField(cryptosweepjob.FieldTotalSwept, field.TypeFloat64, value)
		_node.TotalSwept = value
	}
	if value, ok := _c.mutation.CollectionAddress(); ok {
		_spec.SetField(cryptosweepjob.FieldCollectionAddress, field.TypeString, value)
		_node.CollectionAddress = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(cryptosweepjob.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(cryptosweepjob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoSweepJob.Create().
//		SetNetwork(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoSweepJobUpsert) {
//			SetNetwork(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoSweepJobCreate) OnConflict(opts ...sql.ConflictOption) *CryptoSweepJobUpsertOne {
	_c.conflict = opts
	return &CryptoSweepJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoSweepJobCreate) OnConflictColumns(columns ...string) *CryptoSweepJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoSweepJobUpsertOne{
		create: _c,
	}
}

type (
	// CryptoSweepJobUpsertOne is the builder for "upsert"-ing
	//  one CryptoSweepJob node.
	CryptoSweepJobUpsertOne struct {
		create *CryptoSweepJobCreate
	}

	// CryptoSweepJobUpsert is the "OnConflict" setter.
	CryptoSweepJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetNetwork sets the "network" field.
func (u *CryptoSweepJobUpsert) SetNetwork(v string) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateNetwork() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldNetwork)
	return u
}

// SetStatus sets the "status" field.
func (u *CryptoSweepJobUpsert) SetStatus(v string) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateStatus() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldStatus)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *CryptoSweepJobUpsert) SetCreatedBy(v string) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateCreatedBy() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldCreatedBy)
	return u
}

// SetTotalTasks sets the "total_tasks" field.
func (u *CryptoSweepJobUpsert) SetTotalTasks(v int) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldTotalTasks, v)
	return u
}

// UpdateTotalTasks sets the "total_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateTotalTasks() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldTotalTasks)
	return u
}

// AddTotalTasks adds v to the "total_tasks" field.
func (u *CryptoSweepJobUpsert) AddTotalTasks(v int) *CryptoSweepJobUpsert {
	u.Add(cryptosweepjob.FieldTotalTasks, v)
	return u
}

// SetCompletedTasks sets the "completed_tasks" field.
func (u *CryptoSweepJobUpsert) SetCompletedTasks(v int) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldCompletedTasks, v)
	return u
}

// UpdateCompletedTasks sets the "completed_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateCompletedTasks() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldCompletedTasks)
	return u
}

// AddCompletedTasks adds v to the "completed_tasks" field.
func (u *CryptoSweepJobUpsert) AddCompletedTasks(v int) *CryptoSweepJobUpsert {
	u.Add(cryptosweepjob.FieldCompletedTasks, v)
	return u
}

// SetTotalSwept sets the "total_swept" field.
func (u *CryptoSweepJobUpsert) SetTotalSwept(v float64) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldTotalSwept, v)
	return u
}

// UpdateTotalSwept sets the "total_swept" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateTotalSwept() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldTotalSwept)
	return u
}

// AddTotalSwept adds v to the "total_swept" field.
func (u *CryptoSweepJobUpsert) AddTotalSwept(v float64) *CryptoSweepJobUpsert {
	u.Add(cryptosweepjob.FieldTotalSwept, v)
	return u
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoSweepJobUpsert) SetCollectionAddress(v string) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldCollectionAddress, v)
	return u
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateCollectionAddress() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldCollectionAddress)
	return u
}

// SetError sets the "error" field.
func (u *CryptoSweepJobUpsert) SetError(v string) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateError() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldError)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepJobUpsert) SetUpdatedAt(v time.Time) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateUpdatedAt() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldUpdatedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *CryptoSweepJobUpsert) SetFinishedAt(v time.Time) *CryptoSweepJobUpsert {
	u.Set(cryptosweepjob.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsert) UpdateFinishedAt() *CryptoSweepJobUpsert {
	u.SetExcluded(cryptosweepjob.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CryptoSweepJobUpsert) ClearFinishedAt() *CryptoSweepJobUpsert {
	u.SetNull(cryptosweepjob.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoSweepJobUpsertOne) UpdateNewValues() *CryptoSweepJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cryptosweepjob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CryptoSweepJobUpsertOne) Ignore() *CryptoSweepJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoSweepJobUpsertOne) DoNothing() *CryptoSweepJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoSweepJobCreate.OnConflict
// documentation for more info.
func (u *CryptoSweepJobUpsertOne) Update(set func(*CryptoSweepJobUpsert)) *CryptoSweepJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoSweepJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetNetwork sets the "network" field.
func (u *CryptoSweepJobUpsertOne) SetNetwork(v string) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateNetwork() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateNetwork()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoSweepJobUpsertOne) SetStatus(v string) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateStatus() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CryptoSweepJobUpsertOne) SetCreatedBy(v string) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateCreatedBy() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetTotalTasks sets the "total_tasks" field.
func (u *CryptoSweepJobUpsertOne) SetTotalTasks(v int) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetTotalTasks(v)
	})
}

// AddTotalTasks adds v to the "total_tasks" field.
func (u *CryptoSweepJobUpsertOne) AddTotalTasks(v int) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddTotalTasks(v)
	})
}

// UpdateTotalTasks sets the "total_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateTotalTasks() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateTotalTasks()
	})
}

// SetCompletedTasks sets the "completed_tasks" field.
func (u *CryptoSweepJobUpsertOne) SetCompletedTasks(v int) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCompletedTasks(v)
	})
}

// AddCompletedTasks adds v to the "completed_tasks" field.
func (u *CryptoSweepJobUpsertOne) AddCompletedTasks(v int) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddCompletedTasks(v)
	})
}

// UpdateCompletedTasks sets the "completed_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateCompletedTasks() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCompletedTasks()
	})
}

// SetTotalSwept sets the "total_swept" field.
func (u *CryptoSweepJobUpsertOne) SetTotalSwept(v float64) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetTotalSwept(v)
	})
}

// AddTotalSwept adds v to the "total_swept" field.
func (u *CryptoSweepJobUpsertOne) AddTotalSwept(v float64) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddTotalSwept(v)
	})
}

// UpdateTotalSwept sets the "total_swept" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateTotalSwept() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateTotalSwept()
	})
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoSweepJobUpsertOne) SetCollectionAddress(v string) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCollectionAddress(v)
	})
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateCollectionAddress() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCollectionAddress()
	})
}

// SetError sets the "error" field.
func (u *CryptoSweepJobUpsertOne) SetError(v string) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateError() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepJobUpsertOne) SetUpdatedAt(v time.Time) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateUpdatedAt() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *CryptoSweepJobUpsertOne) SetFinishedAt(v time.Time) *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertOne) UpdateFinishedAt() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CryptoSweepJobUpsertOne) ClearFinishedAt() *CryptoSweepJobUpsertOne {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *CryptoSweepJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoSweepJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoSweepJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CryptoSweepJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CryptoSweepJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CryptoSweepJobCreateBulk is the builder for creating many CryptoSweepJob entities in bulk.
type CryptoSweepJobCreateBulk struct {
	config
	err      error
	builders []*CryptoSweepJobCreate
	conflict []sql.ConflictOption
}

// Save creates the CryptoSweepJob entities in the database.
func (_c *CryptoSweepJobCreateBulk) Save(ctx context.Context) ([]*CryptoSweepJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CryptoSweepJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CryptoSweepJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CryptoSweepJobCreateBulk) SaveX(ctx context.Context) []*CryptoSweepJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CryptoSweepJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CryptoSweepJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CryptoSweepJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CryptoSweepJobUpsert) {
//			SetNetwork(v+v).
//		}).
//		Exec(ctx)
func (_c *CryptoSweepJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *CryptoSweepJobUpsertBulk {
	_c.conflict = opts
	return &CryptoSweepJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CryptoSweepJobCreateBulk) OnConflictColumns(columns ...string) *CryptoSweepJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CryptoSweepJobUpsertBulk{
		create: _c,
	}
}

// CryptoSweepJobUpsertBulk is the builder for "upsert"-ing
// a bulk of CryptoSweepJob nodes.
type CryptoSweepJobUpsertBulk struct {
	create *CryptoSweepJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CryptoSweepJobUpsertBulk) UpdateNewValues() *CryptoSweepJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cryptosweepjob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CryptoSweepJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CryptoSweepJobUpsertBulk) Ignore() *CryptoSweepJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CryptoSweepJobUpsertBulk) DoNothing() *CryptoSweepJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CryptoSweepJobCreateBulk.OnConflict
// documentation for more info.
func (u *CryptoSweepJobUpsertBulk) Update(set func(*CryptoSweepJobUpsert)) *CryptoSweepJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CryptoSweepJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetNetwork sets the "network" field.
func (u *CryptoSweepJobUpsertBulk) SetNetwork(v string) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateNetwork() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateNetwork()
	})
}

// SetStatus sets the "status" field.
func (u *CryptoSweepJobUpsertBulk) SetStatus(v string) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateStatus() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *CryptoSweepJobUpsertBulk) SetCreatedBy(v string) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateCreatedBy() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetTotalTasks sets the "total_tasks" field.
func (u *CryptoSweepJobUpsertBulk) SetTotalTasks(v int) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetTotalTasks(v)
	})
}

// AddTotalTasks adds v to the "total_tasks" field.
func (u *CryptoSweepJobUpsertBulk) AddTotalTasks(v int) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddTotalTasks(v)
	})
}

// UpdateTotalTasks sets the "total_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateTotalTasks() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateTotalTasks()
	})
}

// SetCompletedTasks sets the "completed_tasks" field.
func (u *CryptoSweepJobUpsertBulk) SetCompletedTasks(v int) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCompletedTasks(v)
	})
}

// AddCompletedTasks adds v to the "completed_tasks" field.
func (u *CryptoSweepJobUpsertBulk) AddCompletedTasks(v int) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddCompletedTasks(v)
	})
}

// UpdateCompletedTasks sets the "completed_tasks" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateCompletedTasks() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCompletedTasks()
	})
}

// SetTotalSwept sets the "total_swept" field.
func (u *CryptoSweepJobUpsertBulk) SetTotalSwept(v float64) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetTotalSwept(v)
	})
}

// AddTotalSwept adds v to the "total_swept" field.
func (u *CryptoSweepJobUpsertBulk) AddTotalSwept(v float64) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.AddTotalSwept(v)
	})
}

// UpdateTotalSwept sets the "total_swept" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateTotalSwept() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateTotalSwept()
	})
}

// SetCollectionAddress sets the "collection_address" field.
func (u *CryptoSweepJobUpsertBulk) SetCollectionAddress(v string) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetCollectionAddress(v)
	})
}

// UpdateCollectionAddress sets the "collection_address" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateCollectionAddress() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateCollectionAddress()
	})
}

// SetError sets the "error" field.
func (u *CryptoSweepJobUpsertBulk) SetError(v string) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateError() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateError()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CryptoSweepJobUpsertBulk) SetUpdatedAt(v time.Time) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateUpdatedAt() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *CryptoSweepJobUpsertBulk) SetFinishedAt(v time.Time) *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *CryptoSweepJobUpsertBulk) UpdateFinishedAt() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *CryptoSweepJobUpsertBulk) ClearFinishedAt() *CryptoSweepJobUpsertBulk {
	return u.Update(func(s *CryptoSweepJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *CryptoSweepJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CryptoSweepJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CryptoSweepJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CryptoSweepJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
