// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/trc20consumedtx"
)

// TRC20ConsumedTxUpdate is the builder for updating TRC20ConsumedTx entities.
type TRC20ConsumedTxUpdate struct {
	config
	hooks    []Hook
	mutation *TRC20ConsumedTxMutation
}

// Where appends a list predicates to the TRC20ConsumedTxUpdate builder.
func (_u *TRC20ConsumedTxUpdate) Where(ps ...predicate.TRC20ConsumedTx) *TRC20ConsumedTxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *TRC20ConsumedTxUpdate) SetTxHash(v string) *TRC20ConsumedTxUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdate) SetNillableTxHash(v *string) *TRC20ConsumedTxUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *TRC20ConsumedTxUpdate) SetOrderID(v int64) *TRC20ConsumedTxUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdate) SetNillableOrderID(v *int64) *TRC20ConsumedTxUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *TRC20ConsumedTxUpdate) AddOrderID(v int64) *TRC20ConsumedTxUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *TRC20ConsumedTxUpdate) SetAddress(v string) *TRC20ConsumedTxUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdate) SetNillableAddress(v *string) *TRC20ConsumedTxUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TRC20ConsumedTxUpdate) SetAmount(v float64) *TRC20ConsumedTxUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdate) SetNillableAmount(v *float64) *TRC20ConsumedTxUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TRC20ConsumedTxUpdate) AddAmount(v float64) *TRC20ConsumedTxUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *TRC20ConsumedTxUpdate) SetConfirmedAt(v time.Time) *TRC20ConsumedTxUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdate) SetNillableConfirmedAt(v *time.Time) *TRC20ConsumedTxUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *TRC20ConsumedTxUpdate) ClearConfirmedAt() *TRC20ConsumedTxUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// Mutation returns the TRC20ConsumedTxMutation object of the builder.
func (_u *TRC20ConsumedTxUpdate) Mutation() *TRC20ConsumedTxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TRC20ConsumedTxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TRC20ConsumedTxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TRC20ConsumedTxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TRC20ConsumedTxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TRC20ConsumedTxUpdate) check() error {
	if v, ok := _u.mutation.TxHash(); ok {
		if err := trc20consumedtx.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := trc20consumedtx.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.address": %w`, err)}
		}
	}
	return nil
}

func (_u *TRC20ConsumedTxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trc20consumedtx.Table, trc20consumedtx.Columns, sqlgraph.NewFieldSpec(trc20consumedtx.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(trc20consumedtx.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(trc20consumedtx.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(trc20consumedtx.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(trc20consumedtx.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(trc20consumedtx.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(trc20consumedtx.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(trc20consumedtx.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(trc20consumedtx.FieldConfirmedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trc20consumedtx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TRC20ConsumedTxUpdateOne is the builder for updating a single TRC20ConsumedTx entity.
type TRC20ConsumedTxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TRC20ConsumedTxMutation
}

// SetTxHash sets the "tx_hash" field.
func (_u *TRC20ConsumedTxUpdateOne) SetTxHash(v string) *TRC20ConsumedTxUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdateOne) SetNillableTxHash(v *string) *TRC20ConsumedTxUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *TRC20ConsumedTxUpdateOne) SetOrderID(v int64) *TRC20ConsumedTxUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdateOne) SetNillableOrderID(v *int64) *TRC20ConsumedTxUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *TRC20ConsumedTxUpdateOne) AddOrderID(v int64) *TRC20ConsumedTxUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetAddress sets the "address" field.
func (_u *TRC20ConsumedTxUpdateOne) SetAddress(v string) *TRC20ConsumedTxUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdateOne) SetNillableAddress(v *string) *TRC20ConsumedTxUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TRC20ConsumedTxUpdateOne) SetAmount(v float64) *TRC20ConsumedTxUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdateOne) SetNillableAmount(v *float64) *TRC20ConsumedTxUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TRC20ConsumedTxUpdateOne) AddAmount(v float64) *TRC20ConsumedTxUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *TRC20ConsumedTxUpdateOne) SetConfirmedAt(v time.Time) *TRC20ConsumedTxUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *TRC20ConsumedTxUpdateOne) SetNillableConfirmedAt(v *time.Time) *TRC20ConsumedTxUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *TRC20ConsumedTxUpdateOne) ClearConfirmedAt() *TRC20ConsumedTxUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// Mutation returns the TRC20ConsumedTxMutation object of the builder.
func (_u *TRC20ConsumedTxUpdateOne) Mutation() *TRC20ConsumedTxMutation {
	return _u.mutation
}

// Where appends a list predicates to the TRC20ConsumedTxUpdate builder.
func (_u *TRC20ConsumedTxUpdateOne) Where(ps ...predicate.TRC20ConsumedTx) *TRC20ConsumedTxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TRC20ConsumedTxUpdateOne) Select(field string, fields ...string) *TRC20ConsumedTxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TRC20ConsumedTx entity.
func (_u *TRC20ConsumedTxUpdateOne) Save(ctx context.Context) (*TRC20ConsumedTx, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TRC20ConsumedTxUpdateOne) SaveX(ctx context.Context) *TRC20ConsumedTx {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TRC20ConsumedTxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TRC20ConsumedTxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TRC20ConsumedTxUpdateOne) check() error {
	if v, ok := _u.mutation.TxHash(); ok {
		if err := trc20consumedtx.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := trc20consumedtx.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.address": %w`, err)}
		}
	}
	return nil
}

func (_u *TRC20ConsumedTxUpdateOne) sqlSave(ctx context.Context) (_node *TRC20ConsumedTx, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(trc20consumedtx.Table, trc20consumedtx.Columns, sqlgraph.NewFieldSpec(trc20consumedtx.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TRC20ConsumedTx.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trc20consumedtx.FieldID)
		for _, f := range fields {
			if !trc20consumedtx.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != trc20consumedtx.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(trc20consumedtx.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(trc20consumedtx.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(trc20consumedtx.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(trc20consumedtx.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(trc20consumedtx.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(trc20consumedtx.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(trc20consumedtx.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(trc20consumedtx.FieldConfirmedAt, field.TypeTime)
	}
	_node = &TRC20ConsumedTx{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{trc20consumedtx.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
