// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/trc20consumedtx"
)

// TRC20ConsumedTxCreate is the builder for creating a TRC20ConsumedTx entity.
type TRC20ConsumedTxCreate struct {
	config
	mutation *TRC20ConsumedTxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTxHash sets the "tx_hash" field.
func (_c *TRC20ConsumedTxCreate) SetTxHash(v string) *TRC20ConsumedTxCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *TRC20ConsumedTxCreate) SetNetwork(v string) *TRC20ConsumedTxCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_c *TRC20ConsumedTxCreate) SetNillableNetwork(v *string) *TRC20ConsumedTxCreate {
	if v != nil {
		_c.SetNetwork(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *TRC20ConsumedTxCreate) SetOrderID(v int64) *TRC20ConsumedTxCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *TRC20ConsumedTxCreate) SetAddress(v string) *TRC20ConsumedTxCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TRC20ConsumedTxCreate) SetAmount(v float64) *TRC20ConsumedTxCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *TRC20ConsumedTxCreate) SetConfirmedAt(v time.Time) *TRC20ConsumedTxCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *TRC20ConsumedTxCreate) SetNillableConfirmedAt(v *time.Time) *TRC20ConsumedTxCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TRC20ConsumedTxCreate) SetCreatedAt(v time.Time) *TRC20ConsumedTxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TRC20ConsumedTxCreate) SetNillableCreatedAt(v *time.Time) *TRC20ConsumedTxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the TRC20ConsumedTxMutation object of the builder.
func (_c *TRC20ConsumedTxCreate) Mutation() *TRC20ConsumedTxMutation {
	return _c.mutation
}

// Save creates the TRC20ConsumedTx in the database.
func (_c *TRC20ConsumedTxCreate) Save(ctx context.Context) (*TRC20ConsumedTx, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TRC20ConsumedTxCreate) SaveX(ctx context.Context) *TRC20ConsumedTx {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TRC20ConsumedTxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TRC20ConsumedTxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TRC20ConsumedTxCreate) defaults() {
	if _, ok := _c.mutation.Network(); !ok {
		v := trc20consumedtx.DefaultNetwork
		_c.mutation.SetNetwork(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := trc20consumedtx.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TRC20ConsumedTxCreate) check() error {
	if _, ok := _c.mutation.TxHash(); !ok {
		return &ValidationError{Name: "tx_hash", err: errors.New(`ent: missing required field "TRC20ConsumedTx.tx_hash"`)}
	}
	if v, ok := _c.mutation.TxHash(); ok {
		if err := trc20consumedtx.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.tx_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "TRC20ConsumedTx.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := trc20consumedtx.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "TRC20ConsumedTx.order_id"`)}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "TRC20ConsumedTx.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := trc20consumedtx.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "TRC20ConsumedTx.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TRC20ConsumedTx.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TRC20ConsumedTx.created_at"`)}
	}
	return nil
}

func (_c *TRC20ConsumedTxCreate) sqlSave(ctx context.Context) (*TRC20ConsumedTx, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TRC20ConsumedTxCreate) createSpec() (*TRC20ConsumedTx, *sqlgraph.CreateSpec) {
	var (
		_node = &TRC20ConsumedTx{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(trc20consumedtx.Table, sqlgraph.NewFieldSpec(trc20consumedtx.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(trc20consumedtx.FieldTxHash, field.TypeString, value)
		_node.TxHash = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(trc20consumedtx.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(trc20consumedtx.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(trc20consumedtx.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(trc20consumedtx.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(trc20consumedtx.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(trc20consumedtx.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TRC20ConsumedTx.Create().
//		SetTxHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TRC20ConsumedTxUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *TRC20ConsumedTxCreate) OnConflict(opts ...sql.ConflictOption) *TRC20ConsumedTxUpsertOne {
	_c.conflict = opts
	return &TRC20ConsumedTxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TRC20ConsumedTxCreate) OnConflictColumns(columns ...string) *TRC20ConsumedTxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TRC20ConsumedTxUpsertOne{
		create: _c,
	}
}

type (
	// TRC20ConsumedTxUpsertOne is the builder for "upsert"-ing
	//  one TRC20ConsumedTx node.
	TRC20ConsumedTxUpsertOne struct {
		create *TRC20ConsumedTxCreate
	}

	// TRC20ConsumedTxUpsert is the "OnConflict" setter.
	TRC20ConsumedTxUpsert struct {
		*sql.UpdateSet
	}
)

// SetTxHash sets the "tx_hash" field.
func (u *TRC20ConsumedTxUpsert) SetTxHash(v string) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldTxHash, v)
	return u
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateTxHash() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldTxHash)
	return u
}

// SetNetwork sets the "network" field.
func (u *TRC20ConsumedTxUpsert) SetNetwork(v string) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateNetwork() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldNetwork)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *TRC20ConsumedTxUpsert) SetOrderID(v int64) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateOrderID() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *TRC20ConsumedTxUpsert) AddOrderID(v int64) *TRC20ConsumedTxUpsert {
	u.Add(trc20consumedtx.FieldOrderID, v)
	return u
}

// SetAddress sets the "address" field.
func (u *TRC20ConsumedTxUpsert) SetAddress(v string) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateAddress() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldAddress)
	return u
}

// SetAmount sets the "amount" field.
func (u *TRC20ConsumedTxUpsert) SetAmount(v float64) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateAmount() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *TRC20ConsumedTxUpsert) AddAmount(v float64) *TRC20ConsumedTxUpsert {
	u.Add(trc20consumedtx.FieldAmount, v)
	return u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsert) SetConfirmedAt(v time.Time) *TRC20ConsumedTxUpsert {
	u.Set(trc20consumedtx.FieldConfirmedAt, v)
	return u
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsert) UpdateConfirmedAt() *TRC20ConsumedTxUpsert {
	u.SetExcluded(trc20consumedtx.FieldConfirmedAt)
	return u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsert) ClearConfirmedAt() *TRC20ConsumedTxUpsert {
	u.SetNull(trc20consumedtx.FieldConfirmedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TRC20ConsumedTxUpsertOne) UpdateNewValues() *TRC20ConsumedTxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(trc20consumedtx.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TRC20ConsumedTxUpsertOne) Ignore() *TRC20ConsumedTxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TRC20ConsumedTxUpsertOne) DoNothing() *TRC20ConsumedTxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TRC20ConsumedTxCreate.OnConflict
// documentation for more info.
func (u *TRC20ConsumedTxUpsertOne) Update(set func(*TRC20ConsumedTxUpsert)) *TRC20ConsumedTxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TRC20ConsumedTxUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *TRC20ConsumedTxUpsertOne) SetTxHash(v string) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateTxHash() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateTxHash()
	})
}

// SetNetwork sets the "network" field.
func (u *TRC20ConsumedTxUpsertOne) SetNetwork(v string) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateNetwork() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateNetwork()
	})
}

// SetOrderID sets the "order_id" field.
func (u *TRC20ConsumedTxUpsertOne) SetOrderID(v int64) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *TRC20ConsumedTxUpsertOne) AddOrderID(v int64) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateOrderID() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateOrderID()
	})
}

// SetAddress sets the "address" field.
func (u *TRC20ConsumedTxUpsertOne) SetAddress(v string) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateAddress() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateAddress()
	})
}

// SetAmount sets the "amount" field.
func (u *TRC20ConsumedTxUpsertOne) SetAmount(v float64) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TRC20ConsumedTxUpsertOne) AddAmount(v float64) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateAmount() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateAmount()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsertOne) SetConfirmedAt(v time.Time) *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertOne) UpdateConfirmedAt() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsertOne) ClearConfirmedAt() *TRC20ConsumedTxUpsertOne {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.ClearConfirmedAt()
	})
}

// Exec executes the query.
func (u *TRC20ConsumedTxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TRC20ConsumedTxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TRC20ConsumedTxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TRC20ConsumedTxUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TRC20ConsumedTxUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TRC20ConsumedTxCreateBulk is the builder for creating many TRC20ConsumedTx entities in bulk.
type TRC20ConsumedTxCreateBulk struct {
	config
	err      error
	builders []*TRC20ConsumedTxCreate
	conflict []sql.ConflictOption
}

// Save creates the TRC20ConsumedTx entities in the database.
func (_c *TRC20ConsumedTxCreateBulk) Save(ctx context.Context) ([]*TRC20ConsumedTx, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TRC20ConsumedTx, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TRC20ConsumedTxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TRC20ConsumedTxCreateBulk) SaveX(ctx context.Context) []*TRC20ConsumedTx {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TRC20ConsumedTxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TRC20ConsumedTxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TRC20ConsumedTx.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TRC20ConsumedTxUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *TRC20ConsumedTxCreateBulk) OnConflict(opts ...sql.ConflictOption) *TRC20ConsumedTxUpsertBulk {
	_c.conflict = opts
	return &TRC20ConsumedTxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TRC20ConsumedTxCreateBulk) OnConflictColumns(columns ...string) *TRC20ConsumedTxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TRC20ConsumedTxUpsertBulk{
		create: _c,
	}
}

// TRC20ConsumedTxUpsertBulk is the builder for "upsert"-ing
// a bulk of TRC20ConsumedTx nodes.
type TRC20ConsumedTxUpsertBulk struct {
	create *TRC20ConsumedTxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TRC20ConsumedTxUpsertBulk) UpdateNewValues() *TRC20ConsumedTxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(trc20consumedtx.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TRC20ConsumedTx.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TRC20ConsumedTxUpsertBulk) Ignore() *TRC20ConsumedTxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TRC20ConsumedTxUpsertBulk) DoNothing() *TRC20ConsumedTxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TRC20ConsumedTxCreateBulk.OnConflict
// documentation for more info.
func (u *TRC20ConsumedTxUpsertBulk) Update(set func(*TRC20ConsumedTxUpsert)) *TRC20ConsumedTxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TRC20ConsumedTxUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *TRC20ConsumedTxUpsertBulk) SetTxHash(v string) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateTxHash() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateTxHash()
	})
}

// SetNetwork sets the "network" field.
func (u *TRC20ConsumedTxUpsertBulk) SetNetwork(v string) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateNetwork() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateNetwork()
	})
}

// SetOrderID sets the "order_id" field.
func (u *TRC20ConsumedTxUpsertBulk) SetOrderID(v int64) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *TRC20ConsumedTxUpsertBulk) AddOrderID(v int64) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateOrderID() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateOrderID()
	})
}

// SetAddress sets the "address" field.
func (u *TRC20ConsumedTxUpsertBulk) SetAddress(v string) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateAddress() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateAddress()
	})
}

// SetAmount sets the "amount" field.
func (u *TRC20ConsumedTxUpsertBulk) SetAmount(v float64) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *TRC20ConsumedTxUpsertBulk) AddAmount(v float64) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateAmount() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateAmount()
	})
}

// SetConfirmedAt sets the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsertBulk) SetConfirmedAt(v time.Time) *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.SetConfirmedAt(v)
	})
}

// UpdateConfirmedAt sets the "confirmed_at" field to the value that was provided on create.
func (u *TRC20ConsumedTxUpsertBulk) UpdateConfirmedAt() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.UpdateConfirmedAt()
	})
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (u *TRC20ConsumedTxUpsertBulk) ClearConfirmedAt() *TRC20ConsumedTxUpsertBulk {
	return u.Update(func(s *TRC20ConsumedTxUpsert) {
		s.ClearConfirmedAt()
	})
}

// Exec executes the query.
func (u *TRC20ConsumedTxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TRC20ConsumedTxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TRC20ConsumedTxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TRC20ConsumedTxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
