// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/trc20consumedtx"
)

// TRC20ConsumedTxDelete is the builder for deleting a TRC20ConsumedTx entity.
type TRC20ConsumedTxDelete struct {
	config
	hooks    []Hook
	mutation *TRC20ConsumedTxMutation
}

// Where appends a list predicates to the TRC20ConsumedTxDelete builder.
func (_d *TRC20ConsumedTxDelete) Where(ps ...predicate.TRC20ConsumedTx) *TRC20ConsumedTxDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TRC20ConsumedTxDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TRC20ConsumedTxDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TRC20ConsumedTxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trc20consumedtx.Table, sqlgraph.NewFieldSpec(trc20consumedtx.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TRC20ConsumedTxDeleteOne is the builder for deleting a single TRC20ConsumedTx entity.
type TRC20ConsumedTxDeleteOne struct {
	_d *TRC20ConsumedTxDelete
}

// Where appends a list predicates to the TRC20ConsumedTxDelete builder.
func (_d *TRC20ConsumedTxDeleteOne) Where(ps ...predicate.TRC20ConsumedTx) *TRC20ConsumedTxDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TRC20ConsumedTxDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trc20consumedtx.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TRC20ConsumedTxDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
