// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usercryptoaddress"
)

// UserCryptoAddressCreate is the builder for creating a UserCryptoAddress entity.
type UserCryptoAddressCreate struct {
	config
	mutation *UserCryptoAddressMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *UserCryptoAddressCreate) SetUserID(v int64) *UserCryptoAddressCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *UserCryptoAddressCreate) SetNetwork(v string) *UserCryptoAddressCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableNetwork(v *string) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetNetwork(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *UserCryptoAddressCreate) SetAddress(v string) *UserCryptoAddressCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetDerivationIndex sets the "derivation_index" field.
func (_c *UserCryptoAddressCreate) SetDerivationIndex(v int64) *UserCryptoAddressCreate {
	_c.mutation.SetDerivationIndex(v)
	return _c
}

// SetLastBalance sets the "last_balance" field.
func (_c *UserCryptoAddressCreate) SetLastBalance(v float64) *UserCryptoAddressCreate {
	_c.mutation.SetLastBalance(v)
	return _c
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableLastBalance(v *float64) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetLastBalance(*v)
	}
	return _c
}

// SetLastBalanceUsdc sets the "last_balance_usdc" field.
func (_c *UserCryptoAddressCreate) SetLastBalanceUsdc(v float64) *UserCryptoAddressCreate {
	_c.mutation.SetLastBalanceUsdc(v)
	return _c
}

// SetNillableLastBalanceUsdc sets the "last_balance_usdc" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableLastBalanceUsdc(v *float64) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetLastBalanceUsdc(*v)
	}
	return _c
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (_c *UserCryptoAddressCreate) SetLastBalanceAt(v time.Time) *UserCryptoAddressCreate {
	_c.mutation.SetLastBalanceAt(v)
	return _c
}

// SetNillableLastBalanceAt sets the "last_balance_at" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableLastBalanceAt(v *time.Time) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetLastBalanceAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCryptoAddressCreate) SetCreatedAt(v time.Time) *UserCryptoAddressCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableCreatedAt(v *time.Time) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCryptoAddressCreate) SetUpdatedAt(v time.Time) *UserCryptoAddressCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCryptoAddressCreate) SetNillableUpdatedAt(v *time.Time) *UserCryptoAddressCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserCryptoAddressMutation object of the builder.
func (_c *UserCryptoAddressCreate) Mutation() *UserCryptoAddressMutation {
	return _c.mutation
}

// Save creates the UserCryptoAddress in the database.
func (_c *UserCryptoAddressCreate) Save(ctx context.Context) (*UserCryptoAddress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCryptoAddressCreate) SaveX(ctx context.Context) *UserCryptoAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCryptoAddressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCryptoAddressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCryptoAddressCreate) defaults() {
	if _, ok := _c.mutation.Network(); !ok {
		v := usercryptoaddress.DefaultNetwork
		_c.mutation.SetNetwork(v)
	}
	if _, ok := _c.mutation.LastBalance(); !ok {
		v := usercryptoaddress.DefaultLastBalance
		_c.mutation.SetLastBalance(v)
	}
	if _, ok := _c.mutation.LastBalanceUsdc(); !ok {
		v := usercryptoaddress.DefaultLastBalanceUsdc
		_c.mutation.SetLastBalanceUsdc(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usercryptoaddress.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usercryptoaddress.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCryptoAddressCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserCryptoAddress.user_id"`)}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "UserCryptoAddress.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := usercryptoaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "UserCryptoAddress.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := usercryptoaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DerivationIndex(); !ok {
		return &ValidationError{Name: "derivation_index", err: errors.New(`ent: missing required field "UserCryptoAddress.derivation_index"`)}
	}
	if _, ok := _c.mutation.LastBalance(); !ok {
		return &ValidationError{Name: "last_balance", err: errors.New(`ent: missing required field "UserCryptoAddress.last_balance"`)}
	}
	if _, ok := _c.mutation.LastBalanceUsdc(); !ok {
		return &ValidationError{Name: "last_balance_usdc", err: errors.New(`ent: missing required field "UserCryptoAddress.last_balance_usdc"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserCryptoAddress.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserCryptoAddress.updated_at"`)}
	}
	return nil
}

func (_c *UserCryptoAddressCreate) sqlSave(ctx context.Context) (*UserCryptoAddress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCryptoAddressCreate) createSpec() (*UserCryptoAddress, *sqlgraph.CreateSpec) {
	var (
		_node = &UserCryptoAddress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usercryptoaddress.Table, sqlgraph.NewFieldSpec(usercryptoaddress.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(usercryptoaddress.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(usercryptoaddress.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(usercryptoaddress.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.DerivationIndex(); ok {
		_spec.SetField(usercryptoaddress.FieldDerivationIndex, field.TypeInt64, value)
		_node.DerivationIndex = value
	}
	if value, ok := _c.mutation.LastBalance(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalance, field.TypeFloat64, value)
		_node.LastBalance = value
	}
	if value, ok := _c.mutation.LastBalanceUsdc(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalanceUsdc, field.TypeFloat64, value)
		_node.LastBalanceUsdc = value
	}
	if value, ok := _c.mutation.LastBalanceAt(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalanceAt, field.TypeTime, value)
		_node.LastBalanceAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usercryptoaddress.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usercryptoaddress.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCryptoAddress.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCryptoAddressUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCryptoAddressCreate) OnConflict(opts ...sql.ConflictOption) *UserCryptoAddressUpsertOne {
	_c.conflict = opts
	return &UserCryptoAddressUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCryptoAddressCreate) OnConflictColumns(columns ...string) *UserCryptoAddressUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserCryptoAddressUpsertOne{
		create: _c,
	}
}

type (
	// UserCryptoAddressUpsertOne is the builder for "upsert"-ing
	//  one UserCryptoAddress node.
	UserCryptoAddressUpsertOne struct {
		create *UserCryptoAddressCreate
	}

	// UserCryptoAddressUpsert is the "OnConflict" setter.
	UserCryptoAddressUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *UserCryptoAddressUpsert) SetUserID(v int64) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateUserID() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *UserCryptoAddressUpsert) AddUserID(v int64) *UserCryptoAddressUpsert {
	u.Add(usercryptoaddress.FieldUserID, v)
	return u
}

// SetNetwork sets the "network" field.
func (u *UserCryptoAddressUpsert) SetNetwork(v string) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateNetwork() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldNetwork)
	return u
}

// SetAddress sets the "address" field.
func (u *UserCryptoAddressUpsert) SetAddress(v string) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateAddress() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldAddress)
	return u
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *UserCryptoAddressUpsert) SetDerivationIndex(v int64) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldDerivationIndex, v)
	return u
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateDerivationIndex() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldDerivationIndex)
	return u
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *UserCryptoAddressUpsert) AddDerivationIndex(v int64) *UserCryptoAddressUpsert {
	u.Add(usercryptoaddress.FieldDerivationIndex, v)
	return u
}

// SetLastBalance sets the "last_balance" field.
func (u *UserCryptoAddressUpsert) SetLastBalance(v float64) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldLastBalance, v)
	return u
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateLastBalance() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldLastBalance)
	return u
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UserCryptoAddressUpsert) AddLastBalance(v float64) *UserCryptoAddressUpsert {
	u.Add(usercryptoaddress.FieldLastBalance, v)
	return u
}

// SetLastBalanceUsdc sets the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsert) SetLastBalanceUsdc(v float64) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldLastBalanceUsdc, v)
	return u
}

// UpdateLastBalanceUsdc sets the "last_balance_usdc" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateLastBalanceUsdc() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldLastBalanceUsdc)
	return u
}

// AddLastBalanceUsdc adds v to the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsert) AddLastBalanceUsdc(v float64) *UserCryptoAddressUpsert {
	u.Add(usercryptoaddress.FieldLastBalanceUsdc, v)
	return u
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (u *UserCryptoAddressUpsert) SetLastBalanceAt(v time.Time) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldLastBalanceAt, v)
	return u
}

// UpdateLastBalanceAt sets the "last_balance_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateLastBalanceAt() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldLastBalanceAt)
	return u
}

// ClearLastBalanceAt clears the value of the "last_balance_at" field.
func (u *UserCryptoAddressUpsert) ClearLastBalanceAt() *UserCryptoAddressUpsert {
	u.SetNull(usercryptoaddress.FieldLastBalanceAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserCryptoAddressUpsert) SetUpdatedAt(v time.Time) *UserCryptoAddressUpsert {
	u.Set(usercryptoaddress.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsert) UpdateUpdatedAt() *UserCryptoAddressUpsert {
	u.SetExcluded(usercryptoaddress.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserCryptoAddressUpsertOne) UpdateNewValues() *UserCryptoAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usercryptoaddress.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserCryptoAddressUpsertOne) Ignore() *UserCryptoAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCryptoAddressUpsertOne) DoNothing() *UserCryptoAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCryptoAddressCreate.OnConflict
// documentation for more info.
func (u *UserCryptoAddressUpsertOne) Update(set func(*UserCryptoAddressUpsert)) *UserCryptoAddressUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCryptoAddressUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserCryptoAddressUpsertOne) SetUserID(v int64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserCryptoAddressUpsertOne) AddUserID(v int64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateUserID() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateUserID()
	})
}

// SetNetwork sets the "network" field.
func (u *UserCryptoAddressUpsertOne) SetNetwork(v string) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateNetwork() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateNetwork()
	})
}

// SetAddress sets the "address" field.
func (u *UserCryptoAddressUpsertOne) SetAddress(v string) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateAddress() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateAddress()
	})
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *UserCryptoAddressUpsertOne) SetDerivationIndex(v int64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetDerivationIndex(v)
	})
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *UserCryptoAddressUpsertOne) AddDerivationIndex(v int64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddDerivationIndex(v)
	})
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateDerivationIndex() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateDerivationIndex()
	})
}

// SetLastBalance sets the "last_balance" field.
func (u *UserCryptoAddressUpsertOne) SetLastBalance(v float64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalance(v)
	})
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UserCryptoAddressUpsertOne) AddLastBalance(v float64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddLastBalance(v)
	})
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateLastBalance() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalance()
	})
}

// SetLastBalanceUsdc sets the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsertOne) SetLastBalanceUsdc(v float64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalanceUsdc(v)
	})
}

// AddLastBalanceUsdc adds v to the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsertOne) AddLastBalanceUsdc(v float64) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddLastBalanceUsdc(v)
	})
}

// UpdateLastBalanceUsdc sets the "last_balance_usdc" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateLastBalanceUsdc() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalanceUsdc()
	})
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (u *UserCryptoAddressUpsertOne) SetLastBalanceAt(v time.Time) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalanceAt(v)
	})
}

// UpdateLastBalanceAt sets the "last_balance_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateLastBalanceAt() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalanceAt()
	})
}

// ClearLastBalanceAt clears the value of the "last_balance_at" field.
func (u *UserCryptoAddressUpsertOne) ClearLastBalanceAt() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.ClearLastBalanceAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserCryptoAddressUpsertOne) SetUpdatedAt(v time.Time) *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertOne) UpdateUpdatedAt() *UserCryptoAddressUpsertOne {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserCryptoAddressUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCryptoAddressCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCryptoAddressUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserCryptoAddressUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserCryptoAddressUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCryptoAddressCreateBulk is the builder for creating many UserCryptoAddress entities in bulk.
type UserCryptoAddressCreateBulk struct {
	config
	err      error
	builders []*UserCryptoAddressCreate
	conflict []sql.ConflictOption
}

// Save creates the UserCryptoAddress entities in the database.
func (_c *UserCryptoAddressCreateBulk) Save(ctx context.Context) ([]*UserCryptoAddress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserCryptoAddress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserCryptoAddressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCryptoAddressCreateBulk) SaveX(ctx context.Context) []*UserCryptoAddress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCryptoAddressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCryptoAddressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCryptoAddress.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCryptoAddressUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCryptoAddressCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserCryptoAddressUpsertBulk {
	_c.conflict = opts
	return &UserCryptoAddressUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCryptoAddressCreateBulk) OnConflictColumns(columns ...string) *UserCryptoAddressUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserCryptoAddressUpsertBulk{
		create: _c,
	}
}

// UserCryptoAddressUpsertBulk is the builder for "upsert"-ing
// a bulk of UserCryptoAddress nodes.
type UserCryptoAddressUpsertBulk struct {
	create *UserCryptoAddressCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserCryptoAddressUpsertBulk) UpdateNewValues() *UserCryptoAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usercryptoaddress.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCryptoAddress.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserCryptoAddressUpsertBulk) Ignore() *UserCryptoAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCryptoAddressUpsertBulk) DoNothing() *UserCryptoAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCryptoAddressCreateBulk.OnConflict
// documentation for more info.
func (u *UserCryptoAddressUpsertBulk) Update(set func(*UserCryptoAddressUpsert)) *UserCryptoAddressUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCryptoAddressUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserCryptoAddressUpsertBulk) SetUserID(v int64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *UserCryptoAddressUpsertBulk) AddUserID(v int64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateUserID() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateUserID()
	})
}

// SetNetwork sets the "network" field.
func (u *UserCryptoAddressUpsertBulk) SetNetwork(v string) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateNetwork() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateNetwork()
	})
}

// SetAddress sets the "address" field.
func (u *UserCryptoAddressUpsertBulk) SetAddress(v string) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateAddress() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateAddress()
	})
}

// SetDerivationIndex sets the "derivation_index" field.
func (u *UserCryptoAddressUpsertBulk) SetDerivationIndex(v int64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetDerivationIndex(v)
	})
}

// AddDerivationIndex adds v to the "derivation_index" field.
func (u *UserCryptoAddressUpsertBulk) AddDerivationIndex(v int64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddDerivationIndex(v)
	})
}

// UpdateDerivationIndex sets the "derivation_index" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateDerivationIndex() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateDerivationIndex()
	})
}

// SetLastBalance sets the "last_balance" field.
func (u *UserCryptoAddressUpsertBulk) SetLastBalance(v float64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalance(v)
	})
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UserCryptoAddressUpsertBulk) AddLastBalance(v float64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddLastBalance(v)
	})
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateLastBalance() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalance()
	})
}

// SetLastBalanceUsdc sets the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsertBulk) SetLastBalanceUsdc(v float64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalanceUsdc(v)
	})
}

// AddLastBalanceUsdc adds v to the "last_balance_usdc" field.
func (u *UserCryptoAddressUpsertBulk) AddLastBalanceUsdc(v float64) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.AddLastBalanceUsdc(v)
	})
}

// UpdateLastBalanceUsdc sets the "last_balance_usdc" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateLastBalanceUsdc() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalanceUsdc()
	})
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (u *UserCryptoAddressUpsertBulk) SetLastBalanceAt(v time.Time) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetLastBalanceAt(v)
	})
}

// UpdateLastBalanceAt sets the "last_balance_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateLastBalanceAt() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateLastBalanceAt()
	})
}

// ClearLastBalanceAt clears the value of the "last_balance_at" field.
func (u *UserCryptoAddressUpsertBulk) ClearLastBalanceAt() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.ClearLastBalanceAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserCryptoAddressUpsertBulk) SetUpdatedAt(v time.Time) *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserCryptoAddressUpsertBulk) UpdateUpdatedAt() *UserCryptoAddressUpsertBulk {
	return u.Update(func(s *UserCryptoAddressUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UserCryptoAddressUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCryptoAddressCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCryptoAddressCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCryptoAddressUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
