// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usercryptoaddress"
)

// UserCryptoAddressUpdate is the builder for updating UserCryptoAddress entities.
type UserCryptoAddressUpdate struct {
	config
	hooks    []Hook
	mutation *UserCryptoAddressMutation
}

// Where appends a list predicates to the UserCryptoAddressUpdate builder.
func (_u *UserCryptoAddressUpdate) Where(ps ...predicate.UserCryptoAddress) *UserCryptoAddressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserCryptoAddressUpdate) SetUserID(v int64) *UserCryptoAddressUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableUserID(v *int64) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserCryptoAddressUpdate) AddUserID(v int64) *UserCryptoAddressUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetNetwork sets the "network" field.
func (_u *UserCryptoAddressUpdate) SetNetwork(v string) *UserCryptoAddressUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableNetwork(v *string) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *UserCryptoAddressUpdate) SetAddress(v string) *UserCryptoAddressUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableAddress(v *string) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetDerivationIndex sets the "derivation_index" field.
func (_u *UserCryptoAddressUpdate) SetDerivationIndex(v int64) *UserCryptoAddressUpdate {
	_u.mutation.ResetDerivationIndex()
	_u.mutation.SetDerivationIndex(v)
	return _u
}

// SetNillableDerivationIndex sets the "derivation_index" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableDerivationIndex(v *int64) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetDerivationIndex(*v)
	}
	return _u
}

// AddDerivationIndex adds value to the "derivation_index" field.
func (_u *UserCryptoAddressUpdate) AddDerivationIndex(v int64) *UserCryptoAddressUpdate {
	_u.mutation.AddDerivationIndex(v)
	return _u
}

// SetLastBalance sets the "last_balance" field.
func (_u *UserCryptoAddressUpdate) SetLastBalance(v float64) *UserCryptoAddressUpdate {
	_u.mutation.ResetLastBalance()
	_u.mutation.SetLastBalance(v)
	return _u
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableLastBalance(v *float64) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetLastBalance(*v)
	}
	return _u
}

// AddLastBalance adds value to the "last_balance" field.
func (_u *UserCryptoAddressUpdate) AddLastBalance(v float64) *UserCryptoAddressUpdate {
	_u.mutation.AddLastBalance(v)
	return _u
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (_u *UserCryptoAddressUpdate) SetLastBalanceAt(v time.Time) *UserCryptoAddressUpdate {
	_u.mutation.SetLastBalanceAt(v)
	return _u
}

// SetNillableLastBalanceAt sets the "last_balance_at" field if the given value is not nil.
func (_u *UserCryptoAddressUpdate) SetNillableLastBalanceAt(v *time.Time) *UserCryptoAddressUpdate {
	if v != nil {
		_u.SetLastBalanceAt(*v)
	}
	return _u
}

// ClearLastBalanceAt clears the value of the "last_balance_at" field.
func (_u *UserCryptoAddressUpdate) ClearLastBalanceAt() *UserCryptoAddressUpdate {
	_u.mutation.ClearLastBalanceAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCryptoAddressUpdate) SetUpdatedAt(v time.Time) *UserCryptoAddressUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserCryptoAddressMutation object of the builder.
func (_u *UserCryptoAddressUpdate) Mutation() *UserCryptoAddressMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserCryptoAddressUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCryptoAddressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserCryptoAddressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCryptoAddressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserCryptoAddressUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercryptoaddress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCryptoAddressUpdate) check() error {
	if v, ok := _u.mutation.Network(); ok {
		if err := usercryptoaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usercryptoaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.address": %w`, err)}
		}
	}
	return nil
}

func (_u *UserCryptoAddressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercryptoaddress.Table, usercryptoaddress.Columns, sqlgraph.NewFieldSpec(usercryptoaddress.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usercryptoaddress.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usercryptoaddress.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(usercryptoaddress.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usercryptoaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.DerivationIndex(); ok {
		_spec.SetField(usercryptoaddress.FieldDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDerivationIndex(); ok {
		_spec.AddField(usercryptoaddress.FieldDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastBalance(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastBalance(); ok {
		_spec.AddField(usercryptoaddress.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastBalanceAt(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalanceAt, field.TypeTime, value)
	}
	if _u.mutation.LastBalanceAtCleared() {
		_spec.ClearField(usercryptoaddress.FieldLastBalanceAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercryptoaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercryptoaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserCryptoAddressUpdateOne is the builder for updating a single UserCryptoAddress entity.
type UserCryptoAddressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserCryptoAddressMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserCryptoAddressUpdateOne) SetUserID(v int64) *UserCryptoAddressUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableUserID(v *int64) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserCryptoAddressUpdateOne) AddUserID(v int64) *UserCryptoAddressUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetNetwork sets the "network" field.
func (_u *UserCryptoAddressUpdateOne) SetNetwork(v string) *UserCryptoAddressUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableNetwork(v *string) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *UserCryptoAddressUpdateOne) SetAddress(v string) *UserCryptoAddressUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableAddress(v *string) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetDerivationIndex sets the "derivation_index" field.
func (_u *UserCryptoAddressUpdateOne) SetDerivationIndex(v int64) *UserCryptoAddressUpdateOne {
	_u.mutation.ResetDerivationIndex()
	_u.mutation.SetDerivationIndex(v)
	return _u
}

// SetNillableDerivationIndex sets the "derivation_index" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableDerivationIndex(v *int64) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetDerivationIndex(*v)
	}
	return _u
}

// AddDerivationIndex adds value to the "derivation_index" field.
func (_u *UserCryptoAddressUpdateOne) AddDerivationIndex(v int64) *UserCryptoAddressUpdateOne {
	_u.mutation.AddDerivationIndex(v)
	return _u
}

// SetLastBalance sets the "last_balance" field.
func (_u *UserCryptoAddressUpdateOne) SetLastBalance(v float64) *UserCryptoAddressUpdateOne {
	_u.mutation.ResetLastBalance()
	_u.mutation.SetLastBalance(v)
	return _u
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableLastBalance(v *float64) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetLastBalance(*v)
	}
	return _u
}

// AddLastBalance adds value to the "last_balance" field.
func (_u *UserCryptoAddressUpdateOne) AddLastBalance(v float64) *UserCryptoAddressUpdateOne {
	_u.mutation.AddLastBalance(v)
	return _u
}

// SetLastBalanceAt sets the "last_balance_at" field.
func (_u *UserCryptoAddressUpdateOne) SetLastBalanceAt(v time.Time) *UserCryptoAddressUpdateOne {
	_u.mutation.SetLastBalanceAt(v)
	return _u
}

// SetNillableLastBalanceAt sets the "last_balance_at" field if the given value is not nil.
func (_u *UserCryptoAddressUpdateOne) SetNillableLastBalanceAt(v *time.Time) *UserCryptoAddressUpdateOne {
	if v != nil {
		_u.SetLastBalanceAt(*v)
	}
	return _u
}

// ClearLastBalanceAt clears the value of the "last_balance_at" field.
func (_u *UserCryptoAddressUpdateOne) ClearLastBalanceAt() *UserCryptoAddressUpdateOne {
	_u.mutation.ClearLastBalanceAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserCryptoAddressUpdateOne) SetUpdatedAt(v time.Time) *UserCryptoAddressUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserCryptoAddressMutation object of the builder.
func (_u *UserCryptoAddressUpdateOne) Mutation() *UserCryptoAddressMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserCryptoAddressUpdate builder.
func (_u *UserCryptoAddressUpdateOne) Where(ps ...predicate.UserCryptoAddress) *UserCryptoAddressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserCryptoAddressUpdateOne) Select(field string, fields ...string) *UserCryptoAddressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserCryptoAddress entity.
func (_u *UserCryptoAddressUpdateOne) Save(ctx context.Context) (*UserCryptoAddress, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserCryptoAddressUpdateOne) SaveX(ctx context.Context) *UserCryptoAddress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserCryptoAddressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserCryptoAddressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserCryptoAddressUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usercryptoaddress.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserCryptoAddressUpdateOne) check() error {
	if v, ok := _u.mutation.Network(); ok {
		if err := usercryptoaddress.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usercryptoaddress.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "UserCryptoAddress.address": %w`, err)}
		}
	}
	return nil
}

func (_u *UserCryptoAddressUpdateOne) sqlSave(ctx context.Context) (_node *UserCryptoAddress, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usercryptoaddress.Table, usercryptoaddress.Columns, sqlgraph.NewFieldSpec(usercryptoaddress.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserCryptoAddress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usercryptoaddress.FieldID)
		for _, f := range fields {
			if !usercryptoaddress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usercryptoaddress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usercryptoaddress.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usercryptoaddress.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(usercryptoaddress.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usercryptoaddress.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.DerivationIndex(); ok {
		_spec.SetField(usercryptoaddress.FieldDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDerivationIndex(); ok {
		_spec.AddField(usercryptoaddress.FieldDerivationIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastBalance(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastBalance(); ok {
		_spec.AddField(usercryptoaddress.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.LastBalanceAt(); ok {
		_spec.SetField(usercryptoaddress.FieldLastBalanceAt, field.TypeTime, value)
	}
	if _u.mutation.LastBalanceAtCleared() {
		_spec.ClearField(usercryptoaddress.FieldLastBalanceAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usercryptoaddress.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UserCryptoAddress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usercryptoaddress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
