// Code generated by ent, DO NOT EDIT.

package cryptosweeptask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cryptosweeptask type in the database.
	Label = "crypto_sweep_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldNetwork holds the string denoting the network field in the database.
	FieldNetwork = "network"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldDerivationIndex holds the string denoting the derivation_index field in the database.
	FieldDerivationIndex = "derivation_index"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGasFundTx holds the string denoting the gas_fund_tx field in the database.
	FieldGasFundTx = "gas_fund_tx"
	// FieldSweepTx holds the string denoting the sweep_tx field in the database.
	FieldSweepTx = "sweep_tx"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the cryptosweeptask in the database.
	Table = "crypto_sweep_tasks"
)

// Columns holds all SQL columns for cryptosweeptask fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldNetwork,
	FieldUserID,
	FieldAddress,
	FieldDerivationIndex,
	FieldAmount,
	FieldStatus,
	FieldGasFundTx,
	FieldSweepTx,
	FieldError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNetwork holds the default value on creation for the "network" field.
	DefaultNetwork string
	// NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	NetworkValidator func(string) error
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int64
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultGasFundTx holds the default value on creation for the "gas_fund_tx" field.
	DefaultGasFundTx string
	// GasFundTxValidator is a validator for the "gas_fund_tx" field. It is called by the builders before save.
	GasFundTxValidator func(string) error
	// DefaultSweepTx holds the default value on creation for the "sweep_tx" field.
	DefaultSweepTx string
	// SweepTxValidator is a validator for the "sweep_tx" field. It is called by the builders before save.
	SweepTxValidator func(string) error
	// DefaultError holds the default value on creation for the "error" field.
	DefaultError string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CryptoSweepTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByNetwork orders the results by the network field.
func ByNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetwork, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByDerivationIndex orders the results by the derivation_index field.
func ByDerivationIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDerivationIndex, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGasFundTx orders the results by the gas_fund_tx field.
func ByGasFundTx(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGasFundTx, opts...).ToFunc()
}

// BySweepTx orders the results by the sweep_tx field.
func BySweepTx(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSweepTx, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
