// Code generated by ent, DO NOT EDIT.

package cryptosweeptask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldJobID, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldNetwork, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldUserID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldAddress, v))
}

// DerivationIndex applies equality check predicate on the "derivation_index" field. It's identical to DerivationIndexEQ.
func DerivationIndex(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldDerivationIndex, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldStatus, v))
}

// GasFundTx applies equality check predicate on the "gas_fund_tx" field. It's identical to GasFundTxEQ.
func GasFundTx(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldGasFundTx, v))
}

// SweepTx applies equality check predicate on the "sweep_tx" field. It's identical to SweepTxEQ.
func SweepTx(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldSweepTx, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldJobID, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldNetwork, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldUserID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldAddress, v))
}

// DerivationIndexEQ applies the EQ predicate on the "derivation_index" field.
func DerivationIndexEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldDerivationIndex, v))
}

// DerivationIndexNEQ applies the NEQ predicate on the "derivation_index" field.
func DerivationIndexNEQ(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldDerivationIndex, v))
}

// DerivationIndexIn applies the In predicate on the "derivation_index" field.
func DerivationIndexIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldDerivationIndex, vs...))
}

// DerivationIndexNotIn applies the NotIn predicate on the "derivation_index" field.
func DerivationIndexNotIn(vs ...int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldDerivationIndex, vs...))
}

// DerivationIndexGT applies the GT predicate on the "derivation_index" field.
func DerivationIndexGT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldDerivationIndex, v))
}

// DerivationIndexGTE applies the GTE predicate on the "derivation_index" field.
func DerivationIndexGTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldDerivationIndex, v))
}

// DerivationIndexLT applies the LT predicate on the "derivation_index" field.
func DerivationIndexLT(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldDerivationIndex, v))
}

// DerivationIndexLTE applies the LTE predicate on the "derivation_index" field.
func DerivationIndexLTE(v int64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldDerivationIndex, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldStatus, v))
}

// GasFundTxEQ applies the EQ predicate on the "gas_fund_tx" field.
func GasFundTxEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldGasFundTx, v))
}

// GasFundTxNEQ applies the NEQ predicate on the "gas_fund_tx" field.
func GasFundTxNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldGasFundTx, v))
}

// GasFundTxIn applies the In predicate on the "gas_fund_tx" field.
func GasFundTxIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldGasFundTx, vs...))
}

// GasFundTxNotIn applies the NotIn predicate on the "gas_fund_tx" field.
func GasFundTxNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldGasFundTx, vs...))
}

// GasFundTxGT applies the GT predicate on the "gas_fund_tx" field.
func GasFundTxGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldGasFundTx, v))
}

// GasFundTxGTE applies the GTE predicate on the "gas_fund_tx" field.
func GasFundTxGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldGasFundTx, v))
}

// GasFundTxLT applies the LT predicate on the "gas_fund_tx" field.
func GasFundTxLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldGasFundTx, v))
}

// GasFundTxLTE applies the LTE predicate on the "gas_fund_tx" field.
func GasFundTxLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldGasFundTx, v))
}

// GasFundTxContains applies the Contains predicate on the "gas_fund_tx" field.
func GasFundTxContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldGasFundTx, v))
}

// GasFundTxHasPrefix applies the HasPrefix predicate on the "gas_fund_tx" field.
func GasFundTxHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldGasFundTx, v))
}

// GasFundTxHasSuffix applies the HasSuffix predicate on the "gas_fund_tx" field.
func GasFundTxHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldGasFundTx, v))
}

// GasFundTxEqualFold applies the EqualFold predicate on the "gas_fund_tx" field.
func GasFundTxEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldGasFundTx, v))
}

// GasFundTxContainsFold applies the ContainsFold predicate on the "gas_fund_tx" field.
func GasFundTxContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldGasFundTx, v))
}

// SweepTxEQ applies the EQ predicate on the "sweep_tx" field.
func SweepTxEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldSweepTx, v))
}

// SweepTxNEQ applies the NEQ predicate on the "sweep_tx" field.
func SweepTxNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldSweepTx, v))
}

// SweepTxIn applies the In predicate on the "sweep_tx" field.
func SweepTxIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldSweepTx, vs...))
}

// SweepTxNotIn applies the NotIn predicate on the "sweep_tx" field.
func SweepTxNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldSweepTx, vs...))
}

// SweepTxGT applies the GT predicate on the "sweep_tx" field.
func SweepTxGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldSweepTx, v))
}

// SweepTxGTE applies the GTE predicate on the "sweep_tx" field.
func SweepTxGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldSweepTx, v))
}

// SweepTxLT applies the LT predicate on the "sweep_tx" field.
func SweepTxLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldSweepTx, v))
}

// SweepTxLTE applies the LTE predicate on the "sweep_tx" field.
func SweepTxLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldSweepTx, v))
}

// SweepTxContains applies the Contains predicate on the "sweep_tx" field.
func SweepTxContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldSweepTx, v))
}

// SweepTxHasPrefix applies the HasPrefix predicate on the "sweep_tx" field.
func SweepTxHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldSweepTx, v))
}

// SweepTxHasSuffix applies the HasSuffix predicate on the "sweep_tx" field.
func SweepTxHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldSweepTx, v))
}

// SweepTxEqualFold applies the EqualFold predicate on the "sweep_tx" field.
func SweepTxEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldSweepTx, v))
}

// SweepTxContainsFold applies the ContainsFold predicate on the "sweep_tx" field.
func SweepTxContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldSweepTx, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CryptoSweepTask) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CryptoSweepTask) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CryptoSweepTask) predicate.CryptoSweepTask {
	return predicate.CryptoSweepTask(sql.NotPredicates(p))
}
