// Code generated by ent, DO NOT EDIT.

package trc20consumedtx

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldID, id))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldTxHash, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldOrderID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldAddress, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldAmount, v))
}

// ConfirmedAt applies equality check predicate on the "confirmed_at" field. It's identical to ConfirmedAtEQ.
func ConfirmedAt(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldConfirmedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldCreatedAt, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldContainsFold(FieldTxHash, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldOrderID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldContainsFold(FieldAddress, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldAmount, v))
}

// ConfirmedAtEQ applies the EQ predicate on the "confirmed_at" field.
func ConfirmedAtEQ(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldConfirmedAt, v))
}

// ConfirmedAtNEQ applies the NEQ predicate on the "confirmed_at" field.
func ConfirmedAtNEQ(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldConfirmedAt, v))
}

// ConfirmedAtIn applies the In predicate on the "confirmed_at" field.
func ConfirmedAtIn(vs ...time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtNotIn applies the NotIn predicate on the "confirmed_at" field.
func ConfirmedAtNotIn(vs ...time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldConfirmedAt, vs...))
}

// ConfirmedAtGT applies the GT predicate on the "confirmed_at" field.
func ConfirmedAtGT(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldConfirmedAt, v))
}

// ConfirmedAtGTE applies the GTE predicate on the "confirmed_at" field.
func ConfirmedAtGTE(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldConfirmedAt, v))
}

// ConfirmedAtLT applies the LT predicate on the "confirmed_at" field.
func ConfirmedAtLT(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldConfirmedAt, v))
}

// ConfirmedAtLTE applies the LTE predicate on the "confirmed_at" field.
func ConfirmedAtLTE(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldConfirmedAt, v))
}

// ConfirmedAtIsNil applies the IsNil predicate on the "confirmed_at" field.
func ConfirmedAtIsNil() predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIsNull(FieldConfirmedAt))
}

// ConfirmedAtNotNil applies the NotNil predicate on the "confirmed_at" field.
func ConfirmedAtNotNil() predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotNull(FieldConfirmedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TRC20ConsumedTx) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TRC20ConsumedTx) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TRC20ConsumedTx) predicate.TRC20ConsumedTx {
	return predicate.TRC20ConsumedTx(sql.NotPredicates(p))
}
