// Code generated by ent, DO NOT EDIT.

package cryptowalletconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cryptowalletconfig type in the database.
	Label = "crypto_wallet_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEncryptedMnemonic holds the string denoting the encrypted_mnemonic field in the database.
	FieldEncryptedMnemonic = "encrypted_mnemonic"
	// FieldNextDerivationIndex holds the string denoting the next_derivation_index field in the database.
	FieldNextDerivationIndex = "next_derivation_index"
	// FieldCollectionAddress holds the string denoting the collection_address field in the database.
	FieldCollectionAddress = "collection_address"
	// FieldFeeAddress holds the string denoting the fee_address field in the database.
	FieldFeeAddress = "fee_address"
	// FieldEthCollectionAddress holds the string denoting the eth_collection_address field in the database.
	FieldEthCollectionAddress = "eth_collection_address"
	// FieldEthFeeAddress holds the string denoting the eth_fee_address field in the database.
	FieldEthFeeAddress = "eth_fee_address"
	// FieldInitialized holds the string denoting the initialized field in the database.
	FieldInitialized = "initialized"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the cryptowalletconfig in the database.
	Table = "crypto_wallet_configs"
)

// Columns holds all SQL columns for cryptowalletconfig fields.
var Columns = []string{
	FieldID,
	FieldEncryptedMnemonic,
	FieldNextDerivationIndex,
	FieldCollectionAddress,
	FieldFeeAddress,
	FieldEthCollectionAddress,
	FieldEthFeeAddress,
	FieldInitialized,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEncryptedMnemonic holds the default value on creation for the "encrypted_mnemonic" field.
	DefaultEncryptedMnemonic string
	// DefaultNextDerivationIndex holds the default value on creation for the "next_derivation_index" field.
	DefaultNextDerivationIndex int64
	// DefaultCollectionAddress holds the default value on creation for the "collection_address" field.
	DefaultCollectionAddress string
	// CollectionAddressValidator is a validator for the "collection_address" field. It is called by the builders before save.
	CollectionAddressValidator func(string) error
	// DefaultFeeAddress holds the default value on creation for the "fee_address" field.
	DefaultFeeAddress string
	// FeeAddressValidator is a validator for the "fee_address" field. It is called by the builders before save.
	FeeAddressValidator func(string) error
	// DefaultEthCollectionAddress holds the default value on creation for the "eth_collection_address" field.
	DefaultEthCollectionAddress string
	// EthCollectionAddressValidator is a validator for the "eth_collection_address" field. It is called by the builders before save.
	EthCollectionAddressValidator func(string) error
	// DefaultEthFeeAddress holds the default value on creation for the "eth_fee_address" field.
	DefaultEthFeeAddress string
	// EthFeeAddressValidator is a validator for the "eth_fee_address" field. It is called by the builders before save.
	EthFeeAddressValidator func(string) error
	// DefaultInitialized holds the default value on creation for the "initialized" field.
	DefaultInitialized bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CryptoWalletConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEncryptedMnemonic orders the results by the encrypted_mnemonic field.
func ByEncryptedMnemonic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedMnemonic, opts...).ToFunc()
}

// ByNextDerivationIndex orders the results by the next_derivation_index field.
func ByNextDerivationIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextDerivationIndex, opts...).ToFunc()
}

// ByCollectionAddress orders the results by the collection_address field.
func ByCollectionAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionAddress, opts...).ToFunc()
}

// ByFeeAddress orders the results by the fee_address field.
func ByFeeAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAddress, opts...).ToFunc()
}

// ByEthCollectionAddress orders the results by the eth_collection_address field.
func ByEthCollectionAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEthCollectionAddress, opts...).ToFunc()
}

// ByEthFeeAddress orders the results by the eth_fee_address field.
func ByEthFeeAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEthFeeAddress, opts...).ToFunc()
}

// ByInitialized orders the results by the initialized field.
func ByInitialized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitialized, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
