// Code generated by ent, DO NOT EDIT.

package cryptowalletconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldID, id))
}

// EncryptedMnemonic applies equality check predicate on the "encrypted_mnemonic" field. It's identical to EncryptedMnemonicEQ.
func EncryptedMnemonic(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldEncryptedMnemonic, v))
}

// NextDerivationIndex applies equality check predicate on the "next_derivation_index" field. It's identical to NextDerivationIndexEQ.
func NextDerivationIndex(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldNextDerivationIndex, v))
}

// CollectionAddress applies equality check predicate on the "collection_address" field. It's identical to CollectionAddressEQ.
func CollectionAddress(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldCollectionAddress, v))
}

// FeeAddress applies equality check predicate on the "fee_address" field. It's identical to FeeAddressEQ.
func FeeAddress(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldFeeAddress, v))
}

// Initialized applies equality check predicate on the "initialized" field. It's identical to InitializedEQ.
func Initialized(v bool) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldInitialized, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// EncryptedMnemonicEQ applies the EQ predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicNEQ applies the NEQ predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicNEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicIn applies the In predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldEncryptedMnemonic, vs...))
}

// EncryptedMnemonicNotIn applies the NotIn predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicNotIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldEncryptedMnemonic, vs...))
}

// EncryptedMnemonicGT applies the GT predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicGT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicGTE applies the GTE predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicGTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicLT applies the LT predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicLT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicLTE applies the LTE predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicLTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicContains applies the Contains predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicContains(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContains(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicHasPrefix applies the HasPrefix predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicHasPrefix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasPrefix(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicHasSuffix applies the HasSuffix predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicHasSuffix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasSuffix(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicEqualFold applies the EqualFold predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicEqualFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEqualFold(FieldEncryptedMnemonic, v))
}

// EncryptedMnemonicContainsFold applies the ContainsFold predicate on the "encrypted_mnemonic" field.
func EncryptedMnemonicContainsFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContainsFold(FieldEncryptedMnemonic, v))
}

// NextDerivationIndexEQ applies the EQ predicate on the "next_derivation_index" field.
func NextDerivationIndexEQ(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldNextDerivationIndex, v))
}

// NextDerivationIndexNEQ applies the NEQ predicate on the "next_derivation_index" field.
func NextDerivationIndexNEQ(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldNextDerivationIndex, v))
}

// NextDerivationIndexIn applies the In predicate on the "next_derivation_index" field.
func NextDerivationIndexIn(vs ...int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldNextDerivationIndex, vs...))
}

// NextDerivationIndexNotIn applies the NotIn predicate on the "next_derivation_index" field.
func NextDerivationIndexNotIn(vs ...int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldNextDerivationIndex, vs...))
}

// NextDerivationIndexGT applies the GT predicate on the "next_derivation_index" field.
func NextDerivationIndexGT(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldNextDerivationIndex, v))
}

// NextDerivationIndexGTE applies the GTE predicate on the "next_derivation_index" field.
func NextDerivationIndexGTE(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldNextDerivationIndex, v))
}

// NextDerivationIndexLT applies the LT predicate on the "next_derivation_index" field.
func NextDerivationIndexLT(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldNextDerivationIndex, v))
}

// NextDerivationIndexLTE applies the LTE predicate on the "next_derivation_index" field.
func NextDerivationIndexLTE(v int64) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldNextDerivationIndex, v))
}

// CollectionAddressEQ applies the EQ predicate on the "collection_address" field.
func CollectionAddressEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldCollectionAddress, v))
}

// CollectionAddressNEQ applies the NEQ predicate on the "collection_address" field.
func CollectionAddressNEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldCollectionAddress, v))
}

// CollectionAddressIn applies the In predicate on the "collection_address" field.
func CollectionAddressIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldCollectionAddress, vs...))
}

// CollectionAddressNotIn applies the NotIn predicate on the "collection_address" field.
func CollectionAddressNotIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldCollectionAddress, vs...))
}

// CollectionAddressGT applies the GT predicate on the "collection_address" field.
func CollectionAddressGT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldCollectionAddress, v))
}

// CollectionAddressGTE applies the GTE predicate on the "collection_address" field.
func CollectionAddressGTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldCollectionAddress, v))
}

// CollectionAddressLT applies the LT predicate on the "collection_address" field.
func CollectionAddressLT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldCollectionAddress, v))
}

// CollectionAddressLTE applies the LTE predicate on the "collection_address" field.
func CollectionAddressLTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldCollectionAddress, v))
}

// CollectionAddressContains applies the Contains predicate on the "collection_address" field.
func CollectionAddressContains(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContains(FieldCollectionAddress, v))
}

// CollectionAddressHasPrefix applies the HasPrefix predicate on the "collection_address" field.
func CollectionAddressHasPrefix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasPrefix(FieldCollectionAddress, v))
}

// CollectionAddressHasSuffix applies the HasSuffix predicate on the "collection_address" field.
func CollectionAddressHasSuffix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasSuffix(FieldCollectionAddress, v))
}

// CollectionAddressEqualFold applies the EqualFold predicate on the "collection_address" field.
func CollectionAddressEqualFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEqualFold(FieldCollectionAddress, v))
}

// CollectionAddressContainsFold applies the ContainsFold predicate on the "collection_address" field.
func CollectionAddressContainsFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContainsFold(FieldCollectionAddress, v))
}

// FeeAddressEQ applies the EQ predicate on the "fee_address" field.
func FeeAddressEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldFeeAddress, v))
}

// FeeAddressNEQ applies the NEQ predicate on the "fee_address" field.
func FeeAddressNEQ(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldFeeAddress, v))
}

// FeeAddressIn applies the In predicate on the "fee_address" field.
func FeeAddressIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldFeeAddress, vs...))
}

// FeeAddressNotIn applies the NotIn predicate on the "fee_address" field.
func FeeAddressNotIn(vs ...string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldFeeAddress, vs...))
}

// FeeAddressGT applies the GT predicate on the "fee_address" field.
func FeeAddressGT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldFeeAddress, v))
}

// FeeAddressGTE applies the GTE predicate on the "fee_address" field.
func FeeAddressGTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldFeeAddress, v))
}

// FeeAddressLT applies the LT predicate on the "fee_address" field.
func FeeAddressLT(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldFeeAddress, v))
}

// FeeAddressLTE applies the LTE predicate on the "fee_address" field.
func FeeAddressLTE(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldFeeAddress, v))
}

// FeeAddressContains applies the Contains predicate on the "fee_address" field.
func FeeAddressContains(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContains(FieldFeeAddress, v))
}

// FeeAddressHasPrefix applies the HasPrefix predicate on the "fee_address" field.
func FeeAddressHasPrefix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasPrefix(FieldFeeAddress, v))
}

// FeeAddressHasSuffix applies the HasSuffix predicate on the "fee_address" field.
func FeeAddressHasSuffix(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldHasSuffix(FieldFeeAddress, v))
}

// FeeAddressEqualFold applies the EqualFold predicate on the "fee_address" field.
func FeeAddressEqualFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEqualFold(FieldFeeAddress, v))
}

// FeeAddressContainsFold applies the ContainsFold predicate on the "fee_address" field.
func FeeAddressContainsFold(v string) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldContainsFold(FieldFeeAddress, v))
}

// InitializedEQ applies the EQ predicate on the "initialized" field.
func InitializedEQ(v bool) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldInitialized, v))
}

// InitializedNEQ applies the NEQ predicate on the "initialized" field.
func InitializedNEQ(v bool) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldInitialized, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CryptoWalletConfig) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CryptoWalletConfig) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CryptoWalletConfig) predicate.CryptoWalletConfig {
	return predicate.CryptoWalletConfig(sql.NotPredicates(p))
}
