// Code generated by ent, DO NOT EDIT.

package cryptosweepjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldID, id))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldStatus, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCreatedBy, v))
}

// TotalTasks applies equality check predicate on the "total_tasks" field. It's identical to TotalTasksEQ.
func TotalTasks(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldTotalTasks, v))
}

// CompletedTasks applies equality check predicate on the "completed_tasks" field. It's identical to CompletedTasksEQ.
func CompletedTasks(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCompletedTasks, v))
}

// TotalSwept applies equality check predicate on the "total_swept" field. It's identical to TotalSweptEQ.
func TotalSwept(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldTotalSwept, v))
}

// CollectionAddress applies equality check predicate on the "collection_address" field. It's identical to CollectionAddressEQ.
func CollectionAddress(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCollectionAddress, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldFinishedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContainsFold(FieldCreatedBy, v))
}

// TotalTasksEQ applies the EQ predicate on the "total_tasks" field.
func TotalTasksEQ(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldTotalTasks, v))
}

// TotalTasksNEQ applies the NEQ predicate on the "total_tasks" field.
func TotalTasksNEQ(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldTotalTasks, v))
}

// TotalTasksIn applies the In predicate on the "total_tasks" field.
func TotalTasksIn(vs ...int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldTotalTasks, vs...))
}

// TotalTasksNotIn applies the NotIn predicate on the "total_tasks" field.
func TotalTasksNotIn(vs ...int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldTotalTasks, vs...))
}

// TotalTasksGT applies the GT predicate on the "total_tasks" field.
func TotalTasksGT(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldTotalTasks, v))
}

// TotalTasksGTE applies the GTE predicate on the "total_tasks" field.
func TotalTasksGTE(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldTotalTasks, v))
}

// TotalTasksLT applies the LT predicate on the "total_tasks" field.
func TotalTasksLT(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldTotalTasks, v))
}

// TotalTasksLTE applies the LTE predicate on the "total_tasks" field.
func TotalTasksLTE(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldTotalTasks, v))
}

// CompletedTasksEQ applies the EQ predicate on the "completed_tasks" field.
func CompletedTasksEQ(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCompletedTasks, v))
}

// CompletedTasksNEQ applies the NEQ predicate on the "completed_tasks" field.
func CompletedTasksNEQ(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldCompletedTasks, v))
}

// CompletedTasksIn applies the In predicate on the "completed_tasks" field.
func CompletedTasksIn(vs ...int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldCompletedTasks, vs...))
}

// CompletedTasksNotIn applies the NotIn predicate on the "completed_tasks" field.
func CompletedTasksNotIn(vs ...int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldCompletedTasks, vs...))
}

// CompletedTasksGT applies the GT predicate on the "completed_tasks" field.
func CompletedTasksGT(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldCompletedTasks, v))
}

// CompletedTasksGTE applies the GTE predicate on the "completed_tasks" field.
func CompletedTasksGTE(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldCompletedTasks, v))
}

// CompletedTasksLT applies the LT predicate on the "completed_tasks" field.
func CompletedTasksLT(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldCompletedTasks, v))
}

// CompletedTasksLTE applies the LTE predicate on the "completed_tasks" field.
func CompletedTasksLTE(v int) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldCompletedTasks, v))
}

// TotalSweptEQ applies the EQ predicate on the "total_swept" field.
func TotalSweptEQ(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldTotalSwept, v))
}

// TotalSweptNEQ applies the NEQ predicate on the "total_swept" field.
func TotalSweptNEQ(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldTotalSwept, v))
}

// TotalSweptIn applies the In predicate on the "total_swept" field.
func TotalSweptIn(vs ...float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldTotalSwept, vs...))
}

// TotalSweptNotIn applies the NotIn predicate on the "total_swept" field.
func TotalSweptNotIn(vs ...float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldTotalSwept, vs...))
}

// TotalSweptGT applies the GT predicate on the "total_swept" field.
func TotalSweptGT(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldTotalSwept, v))
}

// TotalSweptGTE applies the GTE predicate on the "total_swept" field.
func TotalSweptGTE(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldTotalSwept, v))
}

// TotalSweptLT applies the LT predicate on the "total_swept" field.
func TotalSweptLT(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldTotalSwept, v))
}

// TotalSweptLTE applies the LTE predicate on the "total_swept" field.
func TotalSweptLTE(v float64) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldTotalSwept, v))
}

// CollectionAddressEQ applies the EQ predicate on the "collection_address" field.
func CollectionAddressEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCollectionAddress, v))
}

// CollectionAddressNEQ applies the NEQ predicate on the "collection_address" field.
func CollectionAddressNEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldCollectionAddress, v))
}

// CollectionAddressIn applies the In predicate on the "collection_address" field.
func CollectionAddressIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldCollectionAddress, vs...))
}

// CollectionAddressNotIn applies the NotIn predicate on the "collection_address" field.
func CollectionAddressNotIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldCollectionAddress, vs...))
}

// CollectionAddressGT applies the GT predicate on the "collection_address" field.
func CollectionAddressGT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldCollectionAddress, v))
}

// CollectionAddressGTE applies the GTE predicate on the "collection_address" field.
func CollectionAddressGTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldCollectionAddress, v))
}

// CollectionAddressLT applies the LT predicate on the "collection_address" field.
func CollectionAddressLT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldCollectionAddress, v))
}

// CollectionAddressLTE applies the LTE predicate on the "collection_address" field.
func CollectionAddressLTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldCollectionAddress, v))
}

// CollectionAddressContains applies the Contains predicate on the "collection_address" field.
func CollectionAddressContains(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContains(FieldCollectionAddress, v))
}

// CollectionAddressHasPrefix applies the HasPrefix predicate on the "collection_address" field.
func CollectionAddressHasPrefix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasPrefix(FieldCollectionAddress, v))
}

// CollectionAddressHasSuffix applies the HasSuffix predicate on the "collection_address" field.
func CollectionAddressHasSuffix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasSuffix(FieldCollectionAddress, v))
}

// CollectionAddressEqualFold applies the EqualFold predicate on the "collection_address" field.
func CollectionAddressEqualFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEqualFold(FieldCollectionAddress, v))
}

// CollectionAddressContainsFold applies the ContainsFold predicate on the "collection_address" field.
func CollectionAddressContainsFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContainsFold(FieldCollectionAddress, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldHasSuffix(FieldError, v))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CryptoSweepJob) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CryptoSweepJob) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CryptoSweepJob) predicate.CryptoSweepJob {
	return predicate.CryptoSweepJob(sql.NotPredicates(p))
}
